--- Copied from https://github.com/VinceG/Auto-Cars-Makes-And-Models


INSERT INTO makes (created_at, updated_at, id, code, name) VALUES
(current_timestamp, current_timestamp, 1, 'ACURA', 'Acura'),
(current_timestamp, current_timestamp, 2, 'ALFA', 'Alfa Romeo'),
(current_timestamp, current_timestamp, 3, 'AMC', 'AMC'),
(current_timestamp, current_timestamp, 4, 'ASTON', 'Aston Martin'),
(current_timestamp, current_timestamp, 5, 'AUDI', 'Audi'),
(current_timestamp, current_timestamp, 6, 'AVANTI', 'Avanti'),
(current_timestamp, current_timestamp, 7, 'BENTL', 'Bentley'),
(current_timestamp, current_timestamp, 8, 'BMW', 'BMW'),
(current_timestamp, current_timestamp, 9, 'BUICK', 'Buick'),
(current_timestamp, current_timestamp, 10, 'CAD', 'Cadillac'),
(current_timestamp, current_timestamp, 11, 'CHEV', 'Chevrolet'),
(current_timestamp, current_timestamp, 12, 'CHRY', 'Chrysler'),
(current_timestamp, current_timestamp, 13, 'DAEW', 'Daewoo'),
(current_timestamp, current_timestamp, 14, 'DAIHAT', 'Daihatsu'),
(current_timestamp, current_timestamp, 15, 'DATSUN', 'Datsun'),
(current_timestamp, current_timestamp, 16, 'DELOREAN', 'DeLorean'),
(current_timestamp, current_timestamp, 17, 'DODGE', 'Dodge'),
(current_timestamp, current_timestamp, 18, 'EAGLE', 'Eagle'),
(current_timestamp, current_timestamp, 19, 'FER', 'Ferrari'),
(current_timestamp, current_timestamp, 20, 'FIAT', 'FIAT'),
(current_timestamp, current_timestamp, 21, 'FISK', 'Fisker'),
(current_timestamp, current_timestamp, 22, 'FORD', 'Ford'),
(current_timestamp, current_timestamp, 23, 'FREIGHT', 'Freightliner'),
(current_timestamp, current_timestamp, 24, 'GEO', 'Geo'),
(current_timestamp, current_timestamp, 25, 'GMC', 'GMC'),
(current_timestamp, current_timestamp, 26, 'HONDA', 'Honda'),
(current_timestamp, current_timestamp, 27, 'AMGEN', 'HUMMER'),
(current_timestamp, current_timestamp, 28, 'HYUND', 'Hyundai'),
(current_timestamp, current_timestamp, 29, 'INFIN', 'Infiniti'),
(current_timestamp, current_timestamp, 30, 'ISU', 'Isuzu'),
(current_timestamp, current_timestamp, 31, 'JAG', 'Jaguar'),
(current_timestamp, current_timestamp, 32, 'JEEP', 'Jeep'),
(current_timestamp, current_timestamp, 33, 'KIA', 'Kia'),
(current_timestamp, current_timestamp, 34, 'LAM', 'Lamborghini'),
(current_timestamp, current_timestamp, 35, 'LAN', 'Lancia'),
(current_timestamp, current_timestamp, 36, 'ROV', 'Land Rover'),
(current_timestamp, current_timestamp, 37, 'LEXUS', 'Lexus'),
(current_timestamp, current_timestamp, 38, 'LINC', 'Lincoln'),
(current_timestamp, current_timestamp, 39, 'LOTUS', 'Lotus'),
(current_timestamp, current_timestamp, 40, 'MAS', 'Maserati'),
(current_timestamp, current_timestamp, 41, 'MAYBACH', 'Maybach'),
(current_timestamp, current_timestamp, 42, 'MAZDA', 'Mazda'),
(current_timestamp, current_timestamp, 43, 'MCLAREN', 'McLaren'),
(current_timestamp, current_timestamp, 44, 'MB', 'Mercedes-Benz'),
(current_timestamp, current_timestamp, 45, 'MERC', 'Mercury'),
(current_timestamp, current_timestamp, 46, 'MERKUR', 'Merkur'),
(current_timestamp, current_timestamp, 47, 'MINI', 'MINI'),
(current_timestamp, current_timestamp, 48, 'MIT', 'Mitsubishi'),
(current_timestamp, current_timestamp, 49, 'NISSAN', 'Nissan'),
(current_timestamp, current_timestamp, 50, 'OLDS', 'Oldsmobile'),
(current_timestamp, current_timestamp, 51, 'PEUG', 'Peugeot'),
(current_timestamp, current_timestamp, 52, 'PLYM', 'Plymouth'),
(current_timestamp, current_timestamp, 53, 'PONT', 'Pontiac'),
(current_timestamp, current_timestamp, 54, 'POR', 'Porsche'),
(current_timestamp, current_timestamp, 55, 'RAM', 'RAM'),
(current_timestamp, current_timestamp, 56, 'REN', 'Renault'),
(current_timestamp, current_timestamp, 57, 'RR', 'Rolls-Royce'),
(current_timestamp, current_timestamp, 58, 'SAAB', 'Saab'),
(current_timestamp, current_timestamp, 59, 'SATURN', 'Saturn'),
(current_timestamp, current_timestamp, 60, 'SCION', 'Scion'),
(current_timestamp, current_timestamp, 61, 'SMART', 'smart'),
(current_timestamp, current_timestamp, 62, 'SRT', 'SRT'),
(current_timestamp, current_timestamp, 63, 'STERL', 'Sterling'),
(current_timestamp, current_timestamp, 64, 'SUB', 'Subaru'),
(current_timestamp, current_timestamp, 65, 'SUZUKI', 'Suzuki'),
(current_timestamp, current_timestamp, 66, 'TESLA', 'Tesla'),
(current_timestamp, current_timestamp, 67, 'TOYOTA', 'Toyota'),
(current_timestamp, current_timestamp, 68, 'TRI', 'Triumph'),
(current_timestamp, current_timestamp, 69, 'VOLKS', 'Volkswagen'),
(current_timestamp, current_timestamp, 70, 'VOLVO', 'Volvo'),
(current_timestamp, current_timestamp, 71, 'YUGO', 'Yugo');

-- ----------------------------------------------------------

INSERT INTO cars (created_at, updated_at, id, make_id, code, model) VALUES
(current_timestamp, current_timestamp, 1, 1, 'CL_MODELS', 'CL Models (4)'),
(current_timestamp, current_timestamp, 2, 1, '2.2CL', ' - 2.2CL'),
(current_timestamp, current_timestamp, 3, 1, '2.3CL', ' - 2.3CL'),
(current_timestamp, current_timestamp, 4, 1, '3.0CL', ' - 3.0CL'),
(current_timestamp, current_timestamp, 5, 1, '3.2CL', ' - 3.2CL'),
(current_timestamp, current_timestamp, 6, 1, 'ILX', 'ILX'),
(current_timestamp, current_timestamp, 7, 1, 'INTEG', 'Integra'),
(current_timestamp, current_timestamp, 8, 1, 'LEGEND', 'Legend'),
(current_timestamp, current_timestamp, 9, 1, 'MDX', 'MDX'),
(current_timestamp, current_timestamp, 10, 1, 'NSX', 'NSX'),
(current_timestamp, current_timestamp, 11, 1, 'RDX', 'RDX'),
(current_timestamp, current_timestamp, 12, 1, 'RL_MODELS', 'RL Models (2)'),
(current_timestamp, current_timestamp, 13, 1, '3.5RL', ' - 3.5 RL'),
(current_timestamp, current_timestamp, 14, 1, 'RL', ' - RL'),
(current_timestamp, current_timestamp, 15, 1, 'RSX', 'RSX'),
(current_timestamp, current_timestamp, 16, 1, 'SLX', 'SLX'),
(current_timestamp, current_timestamp, 17, 1, 'TL_MODELS', 'TL Models (3)'),
(current_timestamp, current_timestamp, 18, 1, '2.5TL', ' - 2.5TL'),
(current_timestamp, current_timestamp, 19, 1, '3.2TL', ' - 3.2TL'),
(current_timestamp, current_timestamp, 20, 1, 'TL', ' - TL'),
(current_timestamp, current_timestamp, 21, 1, 'TSX', 'TSX'),
(current_timestamp, current_timestamp, 22, 1, 'VIGOR', 'Vigor'),
(current_timestamp, current_timestamp, 23, 1, 'ZDX', 'ZDX'),
(current_timestamp, current_timestamp, 24, 1, 'ACUOTH', 'Other Acura Models'),
(current_timestamp, current_timestamp, 25, 2, 'ALFA164', '164'),
(current_timestamp, current_timestamp, 26, 2, 'ALFA8C', '8C Competizione'),
(current_timestamp, current_timestamp, 27, 2, 'ALFAGT', 'GTV-6'),
(current_timestamp, current_timestamp, 28, 2, 'MIL', 'Milano'),
(current_timestamp, current_timestamp, 29, 2, 'SPID', 'Spider'),
(current_timestamp, current_timestamp, 30, 2, 'ALFAOTH', 'Other Alfa Romeo Models'),
(current_timestamp, current_timestamp, 31, 3, 'AMCALLIAN', 'Alliance'),
(current_timestamp, current_timestamp, 32, 3, 'CON', 'Concord'),
(current_timestamp, current_timestamp, 33, 3, 'EAGLE', 'Eagle'),
(current_timestamp, current_timestamp, 34, 3, 'AMCENC', 'Encore'),
(current_timestamp, current_timestamp, 35, 3, 'AMCSPIRIT', 'Spirit'),
(current_timestamp, current_timestamp, 36, 3, 'AMCOTH', 'Other AMC Models'),
(current_timestamp, current_timestamp, 37, 4, 'DB7', 'DB7'),
(current_timestamp, current_timestamp, 38, 4, 'DB9', 'DB9'),
(current_timestamp, current_timestamp, 39, 4, 'DBS', 'DBS'),
(current_timestamp, current_timestamp, 40, 4, 'LAGONDA', 'Lagonda'),
(current_timestamp, current_timestamp, 41, 4, 'RAPIDE', 'Rapide'),
(current_timestamp, current_timestamp, 42, 4, 'V12VANT', 'V12 Vantage'),
(current_timestamp, current_timestamp, 43, 4, 'VANTAGE', 'V8 Vantage'),
(current_timestamp, current_timestamp, 44, 4, 'VANQUISH', 'Vanquish'),
(current_timestamp, current_timestamp, 45, 4, 'VIRAGE', 'Virage'),
(current_timestamp, current_timestamp, 46, 4, 'UNAVAILAST', 'Other Aston Martin Models'),
(current_timestamp, current_timestamp, 47, 5, 'AUDI100', '100'),
(current_timestamp, current_timestamp, 48, 5, 'AUDI200', '200'),
(current_timestamp, current_timestamp, 49, 5, '4000', '4000'),
(current_timestamp, current_timestamp, 50, 5, '5000', '5000'),
(current_timestamp, current_timestamp, 51, 5, '80', '80'),
(current_timestamp, current_timestamp, 52, 5, '90', '90'),
(current_timestamp, current_timestamp, 53, 5, 'A3', 'A3'),
(current_timestamp, current_timestamp, 54, 5, 'A4', 'A4'),
(current_timestamp, current_timestamp, 55, 5, 'A5', 'A5'),
(current_timestamp, current_timestamp, 56, 5, 'A6', 'A6'),
(current_timestamp, current_timestamp, 57, 5, 'A7', 'A7'),
(current_timestamp, current_timestamp, 58, 5, 'A8', 'A8'),
(current_timestamp, current_timestamp, 59, 5, 'ALLRDQUA', 'allroad'),
(current_timestamp, current_timestamp, 60, 5, 'AUDICABRI', 'Cabriolet'),
(current_timestamp, current_timestamp, 61, 5, 'AUDICOUPE', 'Coupe'),
(current_timestamp, current_timestamp, 62, 5, 'Q3', 'Q3'),
(current_timestamp, current_timestamp, 63, 5, 'Q5', 'Q5'),
(current_timestamp, current_timestamp, 64, 5, 'Q7', 'Q7'),
(current_timestamp, current_timestamp, 65, 5, 'QUATTR', 'Quattro'),
(current_timestamp, current_timestamp, 66, 5, 'R8', 'R8'),
(current_timestamp, current_timestamp, 67, 5, 'RS4', 'RS 4'),
(current_timestamp, current_timestamp, 68, 5, 'RS5', 'RS 5'),
(current_timestamp, current_timestamp, 69, 5, 'RS6', 'RS 6'),
(current_timestamp, current_timestamp, 70, 5, 'S4', 'S4'),
(current_timestamp, current_timestamp, 71, 5, 'S5', 'S5'),
(current_timestamp, current_timestamp, 72, 5, 'S6', 'S6'),
(current_timestamp, current_timestamp, 73, 5, 'S7', 'S7'),
(current_timestamp, current_timestamp, 74, 5, 'S8', 'S8'),
(current_timestamp, current_timestamp, 75, 5, 'TT', 'TT'),
(current_timestamp, current_timestamp, 76, 5, 'TTRS', 'TT RS'),
(current_timestamp, current_timestamp, 77, 5, 'TTS', 'TTS'),
(current_timestamp, current_timestamp, 78, 5, 'V8', 'V8 Quattro'),
(current_timestamp, current_timestamp, 79, 5, 'AUDOTH', 'Other Audi Models'),
(current_timestamp, current_timestamp, 80, 6, 'CONVERT', 'Convertible'),
(current_timestamp, current_timestamp, 81, 6, 'COUPEAVANT', 'Coupe'),
(current_timestamp, current_timestamp, 82, 6, 'SEDAN', 'Sedan'),
(current_timestamp, current_timestamp, 83, 6, 'UNAVAILAVA', 'Other Avanti Models'),
(current_timestamp, current_timestamp, 84, 7, 'ARNAGE', 'Arnage'),
(current_timestamp, current_timestamp, 85, 7, 'AZURE', 'Azure'),
(current_timestamp, current_timestamp, 86, 7, 'BROOKLANDS', 'Brooklands'),
(current_timestamp, current_timestamp, 87, 7, 'BENCONT', 'Continental'),
(current_timestamp, current_timestamp, 88, 7, 'CORNICHE', 'Corniche'),
(current_timestamp, current_timestamp, 89, 7, 'BENEIGHT', 'Eight'),
(current_timestamp, current_timestamp, 90, 7, 'BENMUL', 'Mulsanne'),
(current_timestamp, current_timestamp, 91, 7, 'BENTURBO', 'Turbo R'),
(current_timestamp, current_timestamp, 92, 7, 'UNAVAILBEN', 'Other Bentley Models'),
(current_timestamp, current_timestamp, 93, 8, '1_SERIES', '1 Series (3)'),
(current_timestamp, current_timestamp, 94, 8, '128I', ' - 128i'),
(current_timestamp, current_timestamp, 95, 8, '135I', ' - 135i'),
(current_timestamp, current_timestamp, 96, 8, '135IS', ' - 135is'),
(current_timestamp, current_timestamp, 97, 8, '3_SERIES', '3 Series (29)'),
(current_timestamp, current_timestamp, 98, 8, '318I', ' - 318i'),
(current_timestamp, current_timestamp, 99, 8, '318IC', ' - 318iC'),
(current_timestamp, current_timestamp, 100, 8, '318IS', ' - 318iS'),
(current_timestamp, current_timestamp, 101, 8, '318TI', ' - 318ti'),
(current_timestamp, current_timestamp, 102, 8, '320I', ' - 320i'),
(current_timestamp, current_timestamp, 103, 8, '323CI', ' - 323ci'),
(current_timestamp, current_timestamp, 104, 8, '323I', ' - 323i'),
(current_timestamp, current_timestamp, 105, 8, '323IS', ' - 323is'),
(current_timestamp, current_timestamp, 106, 8, '323IT', ' - 323iT'),
(current_timestamp, current_timestamp, 107, 8, '325CI', ' - 325Ci'),
(current_timestamp, current_timestamp, 108, 8, '325E', ' - 325e'),
(current_timestamp, current_timestamp, 109, 8, '325ES', ' - 325es'),
(current_timestamp, current_timestamp, 110, 8, '325I', ' - 325i'),
(current_timestamp, current_timestamp, 111, 8, '325IS', ' - 325is'),
(current_timestamp, current_timestamp, 112, 8, '325IX', ' - 325iX'),
(current_timestamp, current_timestamp, 113, 8, '325XI', ' - 325xi'),
(current_timestamp, current_timestamp, 114, 8, '328CI', ' - 328Ci'),
(current_timestamp, current_timestamp, 115, 8, '328I', ' - 328i'),
(current_timestamp, current_timestamp, 116, 8, '328IS', ' - 328iS'),
(current_timestamp, current_timestamp, 117, 8, '328XI', ' - 328xi'),
(current_timestamp, current_timestamp, 118, 8, '330CI', ' - 330Ci'),
(current_timestamp, current_timestamp, 119, 8, '330I', ' - 330i'),
(current_timestamp, current_timestamp, 120, 8, '330XI', ' - 330xi'),
(current_timestamp, current_timestamp, 121, 8, '335D', ' - 335d'),
(current_timestamp, current_timestamp, 122, 8, '335I', ' - 335i'),
(current_timestamp, current_timestamp, 123, 8, '335IS', ' - 335is'),
(current_timestamp, current_timestamp, 124, 8, '335XI', ' - 335xi'),
(current_timestamp, current_timestamp, 125, 8, 'ACTIVE3', ' - ActiveHybrid 3'),
(current_timestamp, current_timestamp, 126, 8, 'BMW325', ' - 325'),
(current_timestamp, current_timestamp, 127, 8, '5_SERIES', '5 Series (19)'),
(current_timestamp, current_timestamp, 128, 8, '524TD', ' - 524td'),
(current_timestamp, current_timestamp, 129, 8, '525I', ' - 525i'),
(current_timestamp, current_timestamp, 130, 8, '525XI', ' - 525xi'),
(current_timestamp, current_timestamp, 131, 8, '528E', ' - 528e'),
(current_timestamp, current_timestamp, 132, 8, '528I', ' - 528i'),
(current_timestamp, current_timestamp, 133, 8, '528IT', ' - 528iT'),
(current_timestamp, current_timestamp, 134, 8, '528XI', ' - 528xi'),
(current_timestamp, current_timestamp, 135, 8, '530I', ' - 530i'),
(current_timestamp, current_timestamp, 136, 8, '530IT', ' - 530iT'),
(current_timestamp, current_timestamp, 137, 8, '530XI', ' - 530xi'),
(current_timestamp, current_timestamp, 138, 8, '533I', ' - 533i'),
(current_timestamp, current_timestamp, 139, 8, '535I', ' - 535i'),
(current_timestamp, current_timestamp, 140, 8, '535IGT', ' - 535i Gran Turismo'),
(current_timestamp, current_timestamp, 141, 8, '535XI', ' - 535xi'),
(current_timestamp, current_timestamp, 142, 8, '540I', ' - 540i'),
(current_timestamp, current_timestamp, 143, 8, '545I', ' - 545i'),
(current_timestamp, current_timestamp, 144, 8, '550I', ' - 550i'),
(current_timestamp, current_timestamp, 145, 8, '550IGT', ' - 550i Gran Turismo'),
(current_timestamp, current_timestamp, 146, 8, 'ACTIVE5', ' - ActiveHybrid 5'),
(current_timestamp, current_timestamp, 147, 8, '6_SERIES', '6 Series (8)'),
(current_timestamp, current_timestamp, 148, 8, '633CSI', ' - 633CSi'),
(current_timestamp, current_timestamp, 149, 8, '635CSI', ' - 635CSi'),
(current_timestamp, current_timestamp, 150, 8, '640I', ' - 640i'),
(current_timestamp, current_timestamp, 151, 8, '640IGC', ' - 640i Gran Coupe'),
(current_timestamp, current_timestamp, 152, 8, '645CI', ' - 645Ci'),
(current_timestamp, current_timestamp, 153, 8, '650I', ' - 650i'),
(current_timestamp, current_timestamp, 154, 8, '650IGC', ' - 650i Gran Coupe'),
(current_timestamp, current_timestamp, 155, 8, 'L6', ' - L6'),
(current_timestamp, current_timestamp, 156, 8, '7_SERIES', '7 Series (15)'),
(current_timestamp, current_timestamp, 157, 8, '733I', ' - 733i'),
(current_timestamp, current_timestamp, 158, 8, '735I', ' - 735i'),
(current_timestamp, current_timestamp, 159, 8, '735IL', ' - 735iL'),
(current_timestamp, current_timestamp, 160, 8, '740I', ' - 740i'),
(current_timestamp, current_timestamp, 161, 8, '740IL', ' - 740iL'),
(current_timestamp, current_timestamp, 162, 8, '740LI', ' - 740Li'),
(current_timestamp, current_timestamp, 163, 8, '745I', ' - 745i'),
(current_timestamp, current_timestamp, 164, 8, '745LI', ' - 745Li'),
(current_timestamp, current_timestamp, 165, 8, '750I', ' - 750i'),
(current_timestamp, current_timestamp, 166, 8, '750IL', ' - 750iL'),
(current_timestamp, current_timestamp, 167, 8, '750LI', ' - 750Li'),
(current_timestamp, current_timestamp, 168, 8, '760I', ' - 760i'),
(current_timestamp, current_timestamp, 169, 8, '760LI', ' - 760Li'),
(current_timestamp, current_timestamp, 170, 8, 'ACTIVE7', ' - ActiveHybrid 7'),
(current_timestamp, current_timestamp, 171, 8, 'ALPINAB7', ' - Alpina B7'),
(current_timestamp, current_timestamp, 172, 8, '8_SERIES', '8 Series (4)'),
(current_timestamp, current_timestamp, 173, 8, '840CI', ' - 840Ci'),
(current_timestamp, current_timestamp, 174, 8, '850CI', ' - 850Ci'),
(current_timestamp, current_timestamp, 175, 8, '850CSI', ' - 850CSi'),
(current_timestamp, current_timestamp, 176, 8, '850I', ' - 850i'),
(current_timestamp, current_timestamp, 177, 8, 'L_SERIES', 'L Series (1)'),
(current_timestamp, current_timestamp, 178, 8, 'L7', ' - L7'),
(current_timestamp, current_timestamp, 179, 8, 'M_SERIES', 'M Series (8)'),
(current_timestamp, current_timestamp, 180, 8, '1SERIESM', ' - 1 Series M'),
(current_timestamp, current_timestamp, 181, 8, 'BMWMCOUPE', ' - M Coupe'),
(current_timestamp, current_timestamp, 182, 8, 'BMWROAD', ' - M Roadster'),
(current_timestamp, current_timestamp, 183, 8, 'M3', ' - M3'),
(current_timestamp, current_timestamp, 184, 8, 'M5', ' - M5'),
(current_timestamp, current_timestamp, 185, 8, 'M6', ' - M6'),
(current_timestamp, current_timestamp, 186, 8, 'X5M', ' - X5 M'),
(current_timestamp, current_timestamp, 187, 8, 'X6M', ' - X6 M'),
(current_timestamp, current_timestamp, 188, 8, 'X_SERIES', 'X Series (5)'),
(current_timestamp, current_timestamp, 189, 8, 'ACTIVEX6', ' - ActiveHybrid X6'),
(current_timestamp, current_timestamp, 190, 8, 'X1', ' - X1'),
(current_timestamp, current_timestamp, 191, 8, 'X3', ' - X3'),
(current_timestamp, current_timestamp, 192, 8, 'X5', ' - X5'),
(current_timestamp, current_timestamp, 193, 8, 'X6', ' - X6'),
(current_timestamp, current_timestamp, 194, 8, 'Z_SERIES', 'Z Series (3)'),
(current_timestamp, current_timestamp, 195, 8, 'Z3', ' - Z3'),
(current_timestamp, current_timestamp, 196, 8, 'Z4', ' - Z4'),
(current_timestamp, current_timestamp, 197, 8, 'Z8', ' - Z8'),
(current_timestamp, current_timestamp, 198, 8, 'BMWOTH', 'Other BMW Models'),
(current_timestamp, current_timestamp, 199, 9, 'CENT', 'Century'),
(current_timestamp, current_timestamp, 200, 9, 'ELEC', 'Electra'),
(current_timestamp, current_timestamp, 201, 9, 'ENCLAVE', 'Enclave'),
(current_timestamp, current_timestamp, 202, 9, 'BUIENC', 'Encore'),
(current_timestamp, current_timestamp, 203, 9, 'LACROSSE', 'LaCrosse'),
(current_timestamp, current_timestamp, 204, 9, 'LESA', 'Le Sabre'),
(current_timestamp, current_timestamp, 205, 9, 'LUCERNE', 'Lucerne'),
(current_timestamp, current_timestamp, 206, 9, 'PARK', 'Park Avenue'),
(current_timestamp, current_timestamp, 207, 9, 'RAINIER', 'Rainier'),
(current_timestamp, current_timestamp, 208, 9, 'REATTA', 'Reatta'),
(current_timestamp, current_timestamp, 209, 9, 'REG', 'Regal'),
(current_timestamp, current_timestamp, 210, 9, 'RENDEZVOUS', 'Rendezvous'),
(current_timestamp, current_timestamp, 211, 9, 'RIV', 'Riviera'),
(current_timestamp, current_timestamp, 212, 9, 'BUICKROAD', 'Roadmaster'),
(current_timestamp, current_timestamp, 213, 9, 'SKYH', 'Skyhawk'),
(current_timestamp, current_timestamp, 214, 9, 'SKYL', 'Skylark'),
(current_timestamp, current_timestamp, 215, 9, 'SOMER', 'Somerset'),
(current_timestamp, current_timestamp, 216, 9, 'TERRAZA', 'Terraza'),
(current_timestamp, current_timestamp, 217, 9, 'BUVERANO', 'Verano'),
(current_timestamp, current_timestamp, 218, 9, 'BUOTH', 'Other Buick Models'),
(current_timestamp, current_timestamp, 219, 10, 'ALLANT', 'Allante'),
(current_timestamp, current_timestamp, 220, 10, 'ATS', 'ATS'),
(current_timestamp, current_timestamp, 221, 10, 'BROUGH', 'Brougham'),
(current_timestamp, current_timestamp, 222, 10, 'CATERA', 'Catera'),
(current_timestamp, current_timestamp, 223, 10, 'CIMA', 'Cimarron'),
(current_timestamp, current_timestamp, 224, 10, 'CTS', 'CTS'),
(current_timestamp, current_timestamp, 225, 10, 'DEV', 'De Ville'),
(current_timestamp, current_timestamp, 226, 10, 'DTS', 'DTS'),
(current_timestamp, current_timestamp, 227, 10, 'ELDO', 'Eldorado'),
(current_timestamp, current_timestamp, 228, 10, 'ESCALA', 'Escalade'),
(current_timestamp, current_timestamp, 229, 10, 'ESCALAESV', 'Escalade ESV'),
(current_timestamp, current_timestamp, 230, 10, 'EXT', 'Escalade EXT'),
(current_timestamp, current_timestamp, 231, 10, 'FLEE', 'Fleetwood'),
(current_timestamp, current_timestamp, 232, 10, 'SEV', 'Seville'),
(current_timestamp, current_timestamp, 233, 10, 'SRX', 'SRX'),
(current_timestamp, current_timestamp, 234, 10, 'STS', 'STS'),
(current_timestamp, current_timestamp, 235, 10, 'XLR', 'XLR'),
(current_timestamp, current_timestamp, 236, 10, 'XTS', 'XTS'),
(current_timestamp, current_timestamp, 237, 10, 'CADOTH', 'Other Cadillac Models'),
(current_timestamp, current_timestamp, 238, 11, 'ASTRO', 'Astro'),
(current_timestamp, current_timestamp, 239, 11, 'AVALNCH', 'Avalanche'),
(current_timestamp, current_timestamp, 240, 11, 'AVEO', 'Aveo'),
(current_timestamp, current_timestamp, 241, 11, 'AVEO5', 'Aveo5'),
(current_timestamp, current_timestamp, 242, 11, 'BERETT', 'Beretta'),
(current_timestamp, current_timestamp, 243, 11, 'BLAZER', 'Blazer'),
(current_timestamp, current_timestamp, 244, 11, 'CAM', 'Camaro'),
(current_timestamp, current_timestamp, 245, 11, 'CAP', 'Caprice'),
(current_timestamp, current_timestamp, 246, 11, 'CHECAPS', 'Captiva Sport'),
(current_timestamp, current_timestamp, 247, 11, 'CAV', 'Cavalier'),
(current_timestamp, current_timestamp, 248, 11, 'CELE', 'Celebrity'),
(current_timestamp, current_timestamp, 249, 11, 'CHEVETTE', 'Chevette'),
(current_timestamp, current_timestamp, 250, 11, 'CITATION', 'Citation'),
(current_timestamp, current_timestamp, 251, 11, 'COBALT', 'Cobalt'),
(current_timestamp, current_timestamp, 252, 11, 'COLORADO', 'Colorado'),
(current_timestamp, current_timestamp, 253, 11, 'CORSI', 'Corsica'),
(current_timestamp, current_timestamp, 254, 11, 'CORV', 'Corvette'),
(current_timestamp, current_timestamp, 255, 11, 'CRUZE', 'Cruze'),
(current_timestamp, current_timestamp, 256, 11, 'ELCAM', 'El Camino'),
(current_timestamp, current_timestamp, 257, 11, 'EQUINOX', 'Equinox'),
(current_timestamp, current_timestamp, 258, 11, 'G15EXP', 'Express Van'),
(current_timestamp, current_timestamp, 259, 11, 'G10', 'G Van'),
(current_timestamp, current_timestamp, 260, 11, 'HHR', 'HHR'),
(current_timestamp, current_timestamp, 261, 11, 'CHEVIMP', 'Impala'),
(current_timestamp, current_timestamp, 262, 11, 'KODC4500', 'Kodiak C4500'),
(current_timestamp, current_timestamp, 263, 11, 'LUMINA', 'Lumina'),
(current_timestamp, current_timestamp, 264, 11, 'LAPV', 'Lumina APV'),
(current_timestamp, current_timestamp, 265, 11, 'LUV', 'LUV'),
(current_timestamp, current_timestamp, 266, 11, 'MALI', 'Malibu'),
(current_timestamp, current_timestamp, 267, 11, 'CHVMETR', 'Metro'),
(current_timestamp, current_timestamp, 268, 11, 'CHEVMONT', 'Monte Carlo'),
(current_timestamp, current_timestamp, 269, 11, 'NOVA', 'Nova'),
(current_timestamp, current_timestamp, 270, 11, 'CHEVPRIZM', 'Prizm'),
(current_timestamp, current_timestamp, 271, 11, 'CHVST', 'S10 Blazer'),
(current_timestamp, current_timestamp, 272, 11, 'S10PICKUP', 'S10 Pickup'),
(current_timestamp, current_timestamp, 273, 11, 'CHEV150', 'Silverado and other C/K1500'),
(current_timestamp, current_timestamp, 274, 11, 'CHEVC25', 'Silverado and other C/K2500'),
(current_timestamp, current_timestamp, 275, 11, 'CH3500PU', 'Silverado and other C/K3500'),
(current_timestamp, current_timestamp, 276, 11, 'SONIC', 'Sonic'),
(current_timestamp, current_timestamp, 277, 11, 'SPARK', 'Spark'),
(current_timestamp, current_timestamp, 278, 11, 'CHEVSPEC', 'Spectrum'),
(current_timestamp, current_timestamp, 279, 11, 'CHSPRINT', 'Sprint'),
(current_timestamp, current_timestamp, 280, 11, 'SSR', 'SSR'),
(current_timestamp, current_timestamp, 281, 11, 'CHEVSUB', 'Suburban'),
(current_timestamp, current_timestamp, 282, 11, 'TAHOE', 'Tahoe'),
(current_timestamp, current_timestamp, 283, 11, 'TRACKE', 'Tracker'),
(current_timestamp, current_timestamp, 284, 11, 'TRAILBLZ', 'TrailBlazer'),
(current_timestamp, current_timestamp, 285, 11, 'TRAILBZEXT', 'TrailBlazer EXT'),
(current_timestamp, current_timestamp, 286, 11, 'TRAVERSE', 'Traverse'),
(current_timestamp, current_timestamp, 287, 11, 'UPLANDER', 'Uplander'),
(current_timestamp, current_timestamp, 288, 11, 'VENTUR', 'Venture'),
(current_timestamp, current_timestamp, 289, 11, 'VOLT', 'Volt'),
(current_timestamp, current_timestamp, 290, 11, 'CHEOTH', 'Other Chevrolet Models'),
(current_timestamp, current_timestamp, 291, 12, 'CHRYS200', '200'),
(current_timestamp, current_timestamp, 292, 12, '300', '300'),
(current_timestamp, current_timestamp, 293, 12, 'CHRY300', '300M'),
(current_timestamp, current_timestamp, 294, 12, 'ASPEN', 'Aspen'),
(current_timestamp, current_timestamp, 295, 12, 'CARAVAN', 'Caravan'),
(current_timestamp, current_timestamp, 296, 12, 'CIRRUS', 'Cirrus'),
(current_timestamp, current_timestamp, 297, 12, 'CONC', 'Concorde'),
(current_timestamp, current_timestamp, 298, 12, 'CHRYCONQ', 'Conquest'),
(current_timestamp, current_timestamp, 299, 12, 'CORDOBA', 'Cordoba'),
(current_timestamp, current_timestamp, 300, 12, 'CROSSFIRE', 'Crossfire'),
(current_timestamp, current_timestamp, 301, 12, 'ECLASS', 'E Class'),
(current_timestamp, current_timestamp, 302, 12, 'FIFTH', 'Fifth Avenue'),
(current_timestamp, current_timestamp, 303, 12, 'CHRYGRANDV', 'Grand Voyager'),
(current_timestamp, current_timestamp, 304, 12, 'IMPE', 'Imperial'),
(current_timestamp, current_timestamp, 305, 12, 'INTREPID', 'Intrepid'),
(current_timestamp, current_timestamp, 306, 12, 'CHRYLAS', 'Laser'),
(current_timestamp, current_timestamp, 307, 12, 'LEBA', 'LeBaron'),
(current_timestamp, current_timestamp, 308, 12, 'LHS', 'LHS'),
(current_timestamp, current_timestamp, 309, 12, 'CHRYNEON', 'Neon'),
(current_timestamp, current_timestamp, 310, 12, 'NY', 'New Yorker'),
(current_timestamp, current_timestamp, 311, 12, 'NEWPORT', 'Newport'),
(current_timestamp, current_timestamp, 312, 12, 'PACIFICA', 'Pacifica'),
(current_timestamp, current_timestamp, 313, 12, 'CHPROWLE', 'Prowler'),
(current_timestamp, current_timestamp, 314, 12, 'PTCRUIS', 'PT Cruiser'),
(current_timestamp, current_timestamp, 315, 12, 'CHRYSEB', 'Sebring'),
(current_timestamp, current_timestamp, 316, 12, 'CHRYTC', 'TC by Maserati'),
(current_timestamp, current_timestamp, 317, 12, 'TANDC', 'Town & Country'),
(current_timestamp, current_timestamp, 318, 12, 'VOYAGER', 'Voyager'),
(current_timestamp, current_timestamp, 319, 12, 'CHOTH', 'Other Chrysler Models'),
(current_timestamp, current_timestamp, 320, 13, 'LANOS', 'Lanos'),
(current_timestamp, current_timestamp, 321, 13, 'LEGANZA', 'Leganza'),
(current_timestamp, current_timestamp, 322, 13, 'NUBIRA', 'Nubira'),
(current_timestamp, current_timestamp, 323, 13, 'DAEOTH', 'Other Daewoo Models'),
(current_timestamp, current_timestamp, 324, 14, 'CHAR', 'Charade'),
(current_timestamp, current_timestamp, 325, 14, 'ROCKY', 'Rocky'),
(current_timestamp, current_timestamp, 326, 14, 'DAIHOTH', 'Other Daihatsu Models'),
(current_timestamp, current_timestamp, 327, 15, 'DAT200SX', '200SX'),
(current_timestamp, current_timestamp, 328, 15, 'DAT210', '210'),
(current_timestamp, current_timestamp, 329, 15, '280Z', '280ZX'),
(current_timestamp, current_timestamp, 330, 15, '300ZX', '300ZX'),
(current_timestamp, current_timestamp, 331, 15, '310', '310'),
(current_timestamp, current_timestamp, 332, 15, '510', '510'),
(current_timestamp, current_timestamp, 333, 15, '720', '720'),
(current_timestamp, current_timestamp, 334, 15, '810', '810'),
(current_timestamp, current_timestamp, 335, 15, 'DATMAX', 'Maxima'),
(current_timestamp, current_timestamp, 336, 15, 'DATPU', 'Pickup'),
(current_timestamp, current_timestamp, 337, 15, 'PUL', 'Pulsar'),
(current_timestamp, current_timestamp, 338, 15, 'DATSENT', 'Sentra'),
(current_timestamp, current_timestamp, 339, 15, 'STAN', 'Stanza'),
(current_timestamp, current_timestamp, 340, 15, 'DATOTH', 'Other Datsun Models'),
(current_timestamp, current_timestamp, 341, 16, 'DMC12', 'DMC-12'),
(current_timestamp, current_timestamp, 342, 17, '400', '400'),
(current_timestamp, current_timestamp, 343, 17, 'DOD600', '600'),
(current_timestamp, current_timestamp, 344, 17, 'ARI', 'Aries'),
(current_timestamp, current_timestamp, 345, 17, 'AVENGR', 'Avenger'),
(current_timestamp, current_timestamp, 346, 17, 'CALIBER', 'Caliber'),
(current_timestamp, current_timestamp, 347, 17, 'DODCARA', 'Caravan'),
(current_timestamp, current_timestamp, 348, 17, 'CHALLENGER', 'Challenger'),
(current_timestamp, current_timestamp, 349, 17, 'DODCHAR', 'Charger'),
(current_timestamp, current_timestamp, 350, 17, 'DODCOLT', 'Colt'),
(current_timestamp, current_timestamp, 351, 17, 'DODCONQ', 'Conquest'),
(current_timestamp, current_timestamp, 352, 17, 'DODDW', 'D/W Truck'),
(current_timestamp, current_timestamp, 353, 17, 'DAKOTA', 'Dakota'),
(current_timestamp, current_timestamp, 354, 17, 'DODDART', 'Dart'),
(current_timestamp, current_timestamp, 355, 17, 'DAY', 'Daytona'),
(current_timestamp, current_timestamp, 356, 17, 'DIPLOMA', 'Diplomat'),
(current_timestamp, current_timestamp, 357, 17, 'DURANG', 'Durango'),
(current_timestamp, current_timestamp, 358, 17, 'DODDYNA', 'Dynasty'),
(current_timestamp, current_timestamp, 359, 17, 'GRANDCARAV', 'Grand Caravan'),
(current_timestamp, current_timestamp, 360, 17, 'INTRE', 'Intrepid'),
(current_timestamp, current_timestamp, 361, 17, 'JOURNEY', 'Journey'),
(current_timestamp, current_timestamp, 362, 17, 'LANCERDODG', 'Lancer'),
(current_timestamp, current_timestamp, 363, 17, 'MAGNUM', 'Magnum'),
(current_timestamp, current_timestamp, 364, 17, 'MIRADA', 'Mirada'),
(current_timestamp, current_timestamp, 365, 17, 'MONACO', 'Monaco'),
(current_timestamp, current_timestamp, 366, 17, 'DODNEON', 'Neon'),
(current_timestamp, current_timestamp, 367, 17, 'NITRO', 'Nitro'),
(current_timestamp, current_timestamp, 368, 17, 'OMNI', 'Omni'),
(current_timestamp, current_timestamp, 369, 17, 'RAIDER', 'Raider'),
(current_timestamp, current_timestamp, 370, 17, 'RAM1504WD', 'Ram 1500 Truck'),
(current_timestamp, current_timestamp, 371, 17, 'RAM25002WD', 'Ram 2500 Truck'),
(current_timestamp, current_timestamp, 372, 17, 'RAM3502WD', 'Ram 3500 Truck'),
(current_timestamp, current_timestamp, 373, 17, 'RAM4500', 'Ram 4500 Truck'),
(current_timestamp, current_timestamp, 374, 17, 'DODD50', 'Ram 50 Truck'),
(current_timestamp, current_timestamp, 375, 17, 'CV', 'RAM C/V'),
(current_timestamp, current_timestamp, 376, 17, 'RAMSRT10', 'Ram SRT-10'),
(current_timestamp, current_timestamp, 377, 17, 'RAMVANV8', 'Ram Van'),
(current_timestamp, current_timestamp, 378, 17, 'RAMWAGON', 'Ram Wagon'),
(current_timestamp, current_timestamp, 379, 17, 'RAMCGR', 'Ramcharger'),
(current_timestamp, current_timestamp, 380, 17, 'RAMPAGE', 'Rampage'),
(current_timestamp, current_timestamp, 381, 17, 'DODSHAD', 'Shadow'),
(current_timestamp, current_timestamp, 382, 17, 'DODSPIR', 'Spirit'),
(current_timestamp, current_timestamp, 383, 17, 'SPRINTER', 'Sprinter'),
(current_timestamp, current_timestamp, 384, 17, 'SRT4', 'SRT-4'),
(current_timestamp, current_timestamp, 385, 17, 'STREGIS', 'St. Regis'),
(current_timestamp, current_timestamp, 386, 17, 'STEAL', 'Stealth'),
(current_timestamp, current_timestamp, 387, 17, 'STRATU', 'Stratus'),
(current_timestamp, current_timestamp, 388, 17, 'VIPER', 'Viper'),
(current_timestamp, current_timestamp, 389, 17, 'DOOTH', 'Other Dodge Models'),
(current_timestamp, current_timestamp, 390, 18, 'EAGLEMED', 'Medallion'),
(current_timestamp, current_timestamp, 391, 18, 'EAGLEPREM', 'Premier'),
(current_timestamp, current_timestamp, 392, 18, 'SUMMIT', 'Summit'),
(current_timestamp, current_timestamp, 393, 18, 'TALON', 'Talon'),
(current_timestamp, current_timestamp, 394, 18, 'VISION', 'Vision'),
(current_timestamp, current_timestamp, 395, 18, 'EAGOTH', 'Other Eagle Models'),
(current_timestamp, current_timestamp, 396, 19, '308GTB', '308 GTB Quattrovalvole'),
(current_timestamp, current_timestamp, 397, 19, '308TBI', '308 GTBI'),
(current_timestamp, current_timestamp, 398, 19, '308GTS', '308 GTS Quattrovalvole'),
(current_timestamp, current_timestamp, 399, 19, '308TSI', '308 GTSI'),
(current_timestamp, current_timestamp, 400, 19, '328GTB', '328 GTB'),
(current_timestamp, current_timestamp, 401, 19, '328GTS', '328 GTS'),
(current_timestamp, current_timestamp, 402, 19, '348GTB', '348 GTB'),
(current_timestamp, current_timestamp, 403, 19, '348GTS', '348 GTS'),
(current_timestamp, current_timestamp, 404, 19, '348SPI', '348 Spider'),
(current_timestamp, current_timestamp, 405, 19, '348TB', '348 TB'),
(current_timestamp, current_timestamp, 406, 19, '348TS', '348 TS'),
(current_timestamp, current_timestamp, 407, 19, '360', '360'),
(current_timestamp, current_timestamp, 408, 19, '456GT', '456 GT'),
(current_timestamp, current_timestamp, 409, 19, '456MGT', '456M GT'),
(current_timestamp, current_timestamp, 410, 19, '458ITALIA', '458 Italia'),
(current_timestamp, current_timestamp, 411, 19, '512BBI', '512 BBi'),
(current_timestamp, current_timestamp, 412, 19, '512M', '512M'),
(current_timestamp, current_timestamp, 413, 19, '512TR', '512TR'),
(current_timestamp, current_timestamp, 414, 19, '550M', '550 Maranello'),
(current_timestamp, current_timestamp, 415, 19, '575M', '575M Maranello'),
(current_timestamp, current_timestamp, 416, 19, '599GTB', '599 GTB Fiorano'),
(current_timestamp, current_timestamp, 417, 19, '599GTO', '599 GTO'),
(current_timestamp, current_timestamp, 418, 19, '612SCAGLIE', '612 Scaglietti'),
(current_timestamp, current_timestamp, 419, 19, 'FERCALIF', 'California'),
(current_timestamp, current_timestamp, 420, 19, 'ENZO', 'Enzo'),
(current_timestamp, current_timestamp, 421, 19, 'F355', 'F355'),
(current_timestamp, current_timestamp, 422, 19, 'F40', 'F40'),
(current_timestamp, current_timestamp, 423, 19, 'F430', 'F430'),
(current_timestamp, current_timestamp, 424, 19, 'F50', 'F50'),
(current_timestamp, current_timestamp, 425, 19, 'FERFF', 'FF'),
(current_timestamp, current_timestamp, 426, 19, 'MOND', 'Mondial'),
(current_timestamp, current_timestamp, 427, 19, 'TEST', 'Testarossa'),
(current_timestamp, current_timestamp, 428, 19, 'UNAVAILFER', 'Other Ferrari Models'),
(current_timestamp, current_timestamp, 429, 20, '2000', '2000 Spider'),
(current_timestamp, current_timestamp, 430, 20, 'FIAT500', '500'),
(current_timestamp, current_timestamp, 431, 20, 'BERTON', 'Bertone X1/9'),
(current_timestamp, current_timestamp, 432, 20, 'BRAVA', 'Brava'),
(current_timestamp, current_timestamp, 433, 20, 'PININ', 'Pininfarina Spider'),
(current_timestamp, current_timestamp, 434, 20, 'STRADA', 'Strada'),
(current_timestamp, current_timestamp, 435, 20, 'FIATX19', 'X1/9'),
(current_timestamp, current_timestamp, 436, 20, 'UNAVAILFIA', 'Other Fiat Models'),
(current_timestamp, current_timestamp, 437, 21, 'KARMA', 'Karma'),
(current_timestamp, current_timestamp, 438, 22, 'AERO', 'Aerostar'),
(current_timestamp, current_timestamp, 439, 22, 'ASPIRE', 'Aspire'),
(current_timestamp, current_timestamp, 440, 22, 'BRON', 'Bronco'),
(current_timestamp, current_timestamp, 441, 22, 'B2', 'Bronco II'),
(current_timestamp, current_timestamp, 442, 22, 'FOCMAX', 'C-MAX'),
(current_timestamp, current_timestamp, 443, 22, 'FORDCLUB', 'Club Wagon'),
(current_timestamp, current_timestamp, 444, 22, 'CONTOUR', 'Contour'),
(current_timestamp, current_timestamp, 445, 22, 'COURIER', 'Courier'),
(current_timestamp, current_timestamp, 446, 22, 'CROWNVIC', 'Crown Victoria'),
(current_timestamp, current_timestamp, 447, 22, 'E150ECON', 'E-150 and Econoline 150'),
(current_timestamp, current_timestamp, 448, 22, 'E250ECON', 'E-250 and Econoline 250'),
(current_timestamp, current_timestamp, 449, 22, 'E350ECON', 'E-350 and Econoline 350'),
(current_timestamp, current_timestamp, 450, 22, 'EDGE', 'Edge'),
(current_timestamp, current_timestamp, 451, 22, 'ESCAPE', 'Escape'),
(current_timestamp, current_timestamp, 452, 22, 'ESCO', 'Escort'),
(current_timestamp, current_timestamp, 453, 22, 'EXCURSION', 'Excursion'),
(current_timestamp, current_timestamp, 454, 22, 'EXP', 'EXP'),
(current_timestamp, current_timestamp, 455, 22, 'EXPEDI', 'Expedition'),
(current_timestamp, current_timestamp, 456, 22, 'EXPEDIEL', 'Expedition EL'),
(current_timestamp, current_timestamp, 457, 22, 'EXPLOR', 'Explorer'),
(current_timestamp, current_timestamp, 458, 22, 'SPORTTRAC', 'Explorer Sport Trac'),
(current_timestamp, current_timestamp, 459, 22, 'F100', 'F100'),
(current_timestamp, current_timestamp, 460, 22, 'F150PICKUP', 'F150'),
(current_timestamp, current_timestamp, 461, 22, 'F250', 'F250'),
(current_timestamp, current_timestamp, 462, 22, 'F350', 'F350'),
(current_timestamp, current_timestamp, 463, 22, 'F450', 'F450'),
(current_timestamp, current_timestamp, 464, 22, 'FAIRM', 'Fairmont'),
(current_timestamp, current_timestamp, 465, 22, 'FESTIV', 'Festiva'),
(current_timestamp, current_timestamp, 466, 22, 'FIESTA', 'Fiesta'),
(current_timestamp, current_timestamp, 467, 22, 'FIVEHUNDRE', 'Five Hundred'),
(current_timestamp, current_timestamp, 468, 22, 'FLEX', 'Flex'),
(current_timestamp, current_timestamp, 469, 22, 'FOCUS', 'Focus'),
(current_timestamp, current_timestamp, 470, 22, 'FREESTAR', 'Freestar'),
(current_timestamp, current_timestamp, 471, 22, 'FREESTYLE', 'Freestyle'),
(current_timestamp, current_timestamp, 472, 22, 'FUSION', 'Fusion'),
(current_timestamp, current_timestamp, 473, 22, 'GRANADA', 'Granada'),
(current_timestamp, current_timestamp, 474, 22, 'GT', 'GT'),
(current_timestamp, current_timestamp, 475, 22, 'LTD', 'LTD'),
(current_timestamp, current_timestamp, 476, 22, 'MUST', 'Mustang'),
(current_timestamp, current_timestamp, 477, 22, 'PROBE', 'Probe'),
(current_timestamp, current_timestamp, 478, 22, 'RANGER', 'Ranger'),
(current_timestamp, current_timestamp, 479, 22, 'TAURUS', 'Taurus'),
(current_timestamp, current_timestamp, 480, 22, 'TAURUSX', 'Taurus X'),
(current_timestamp, current_timestamp, 481, 22, 'TEMPO', 'Tempo'),
(current_timestamp, current_timestamp, 482, 22, 'TBIRD', 'Thunderbird'),
(current_timestamp, current_timestamp, 483, 22, 'TRANSCONN', 'Transit Connect'),
(current_timestamp, current_timestamp, 484, 22, 'WINDST', 'Windstar'),
(current_timestamp, current_timestamp, 485, 22, 'FORDZX2', 'ZX2 Escort'),
(current_timestamp, current_timestamp, 486, 22, 'FOOTH', 'Other Ford Models'),
(current_timestamp, current_timestamp, 487, 23, 'FRESPRINT', 'Sprinter'),
(current_timestamp, current_timestamp, 488, 24, 'GEOMETRO', 'Metro'),
(current_timestamp, current_timestamp, 489, 24, 'GEOPRIZM', 'Prizm'),
(current_timestamp, current_timestamp, 490, 24, 'SPECT', 'Spectrum'),
(current_timestamp, current_timestamp, 491, 24, 'STORM', 'Storm'),
(current_timestamp, current_timestamp, 492, 24, 'GEOTRACK', 'Tracker'),
(current_timestamp, current_timestamp, 493, 24, 'GEOOTH', 'Other Geo Models'),
(current_timestamp, current_timestamp, 494, 25, 'ACADIA', 'Acadia'),
(current_timestamp, current_timestamp, 495, 25, 'CABALLERO', 'Caballero'),
(current_timestamp, current_timestamp, 496, 25, 'CANYON', 'Canyon'),
(current_timestamp, current_timestamp, 497, 25, 'ENVOY', 'Envoy'),
(current_timestamp, current_timestamp, 498, 25, 'ENVOYXL', 'Envoy XL'),
(current_timestamp, current_timestamp, 499, 25, 'ENVOYXUV', 'Envoy XUV'),
(current_timestamp, current_timestamp, 500, 25, 'JIM', 'Jimmy'),
(current_timestamp, current_timestamp, 501, 25, 'RALLYWAG', 'Rally Wagon'),
(current_timestamp, current_timestamp, 502, 25, 'GMCS15', 'S15 Jimmy'),
(current_timestamp, current_timestamp, 503, 25, 'S15', 'S15 Pickup'),
(current_timestamp, current_timestamp, 504, 25, 'SAFARIGMC', 'Safari'),
(current_timestamp, current_timestamp, 505, 25, 'GMCSAVANA', 'Savana'),
(current_timestamp, current_timestamp, 506, 25, '15SIPU4WD', 'Sierra C/K1500'),
(current_timestamp, current_timestamp, 507, 25, 'GMCC25PU', 'Sierra C/K2500'),
(current_timestamp, current_timestamp, 508, 25, 'GMC3500PU', 'Sierra C/K3500'),
(current_timestamp, current_timestamp, 509, 25, 'SONOMA', 'Sonoma'),
(current_timestamp, current_timestamp, 510, 25, 'SUB', 'Suburban'),
(current_timestamp, current_timestamp, 511, 25, 'GMCSYCLON', 'Syclone'),
(current_timestamp, current_timestamp, 512, 25, 'TERRAIN', 'Terrain'),
(current_timestamp, current_timestamp, 513, 25, 'TOPC4500', 'TopKick C4500'),
(current_timestamp, current_timestamp, 514, 25, 'TYPH', 'Typhoon'),
(current_timestamp, current_timestamp, 515, 25, 'GMCVANDUR', 'Vandura'),
(current_timestamp, current_timestamp, 516, 25, 'YUKON', 'Yukon'),
(current_timestamp, current_timestamp, 517, 25, 'YUKONXL', 'Yukon XL'),
(current_timestamp, current_timestamp, 518, 25, 'GMCOTH', 'Other GMC Models'),
(current_timestamp, current_timestamp, 519, 26, 'ACCORD', 'Accord'),
(current_timestamp, current_timestamp, 520, 26, 'CIVIC', 'Civic'),
(current_timestamp, current_timestamp, 521, 26, 'CRV', 'CR-V'),
(current_timestamp, current_timestamp, 522, 26, 'CRZ', 'CR-Z'),
(current_timestamp, current_timestamp, 523, 26, 'CRX', 'CRX'),
(current_timestamp, current_timestamp, 524, 26, 'CROSSTOUR_MODELS', 'Crosstour and Accord Crosstour Models (2)'),
(current_timestamp, current_timestamp, 525, 26, 'CROSSTOUR', ' - Accord Crosstour'),
(current_timestamp, current_timestamp, 526, 26, 'HONCROSS', ' - Crosstour'),
(current_timestamp, current_timestamp, 527, 26, 'HONDELSOL', 'Del Sol'),
(current_timestamp, current_timestamp, 528, 26, 'ELEMENT', 'Element'),
(current_timestamp, current_timestamp, 529, 26, 'FIT', 'Fit'),
(current_timestamp, current_timestamp, 530, 26, 'INSIGHT', 'Insight'),
(current_timestamp, current_timestamp, 531, 26, 'ODYSSEY', 'Odyssey'),
(current_timestamp, current_timestamp, 532, 26, 'PASSPO', 'Passport'),
(current_timestamp, current_timestamp, 533, 26, 'PILOT', 'Pilot'),
(current_timestamp, current_timestamp, 534, 26, 'PRE', 'Prelude'),
(current_timestamp, current_timestamp, 535, 26, 'RIDGELINE', 'Ridgeline'),
(current_timestamp, current_timestamp, 536, 26, 'S2000', 'S2000'),
(current_timestamp, current_timestamp, 537, 26, 'HONOTH', 'Other Honda Models'),
(current_timestamp, current_timestamp, 538, 27, 'HUMMER', 'H1'),
(current_timestamp, current_timestamp, 539, 27, 'H2', 'H2'),
(current_timestamp, current_timestamp, 540, 27, 'H3', 'H3'),
(current_timestamp, current_timestamp, 541, 27, 'H3T', 'H3T'),
(current_timestamp, current_timestamp, 542, 27, 'AMGOTH', 'Other Hummer Models'),
(current_timestamp, current_timestamp, 543, 28, 'ACCENT', 'Accent'),
(current_timestamp, current_timestamp, 544, 28, 'AZERA', 'Azera'),
(current_timestamp, current_timestamp, 545, 28, 'ELANTR', 'Elantra'),
(current_timestamp, current_timestamp, 546, 28, 'HYUELANCPE', 'Elantra Coupe'),
(current_timestamp, current_timestamp, 547, 28, 'ELANTOUR', 'Elantra Touring'),
(current_timestamp, current_timestamp, 548, 28, 'ENTOURAGE', 'Entourage'),
(current_timestamp, current_timestamp, 549, 28, 'EQUUS', 'Equus'),
(current_timestamp, current_timestamp, 550, 28, 'HYUEXCEL', 'Excel'),
(current_timestamp, current_timestamp, 551, 28, 'GENESIS', 'Genesis'),
(current_timestamp, current_timestamp, 552, 28, 'GENESISCPE', 'Genesis Coupe'),
(current_timestamp, current_timestamp, 553, 28, 'SANTAFE', 'Santa Fe'),
(current_timestamp, current_timestamp, 554, 28, 'SCOUPE', 'Scoupe'),
(current_timestamp, current_timestamp, 555, 28, 'SONATA', 'Sonata'),
(current_timestamp, current_timestamp, 556, 28, 'TIBURO', 'Tiburon'),
(current_timestamp, current_timestamp, 557, 28, 'TUCSON', 'Tucson'),
(current_timestamp, current_timestamp, 558, 28, 'VELOSTER', 'Veloster'),
(current_timestamp, current_timestamp, 559, 28, 'VERACRUZ', 'Veracruz'),
(current_timestamp, current_timestamp, 560, 28, 'XG300', 'XG300'),
(current_timestamp, current_timestamp, 561, 28, 'XG350', 'XG350'),
(current_timestamp, current_timestamp, 562, 28, 'HYUOTH', 'Other Hyundai Models'),
(current_timestamp, current_timestamp, 563, 29, 'EX_MODELS', 'EX Models (2)'),
(current_timestamp, current_timestamp, 564, 29, 'EX35', ' - EX35'),
(current_timestamp, current_timestamp, 565, 29, 'EX37', ' - EX37'),
(current_timestamp, current_timestamp, 566, 29, 'FX_MODELS', 'FX Models (4)'),
(current_timestamp, current_timestamp, 567, 29, 'FX35', ' - FX35'),
(current_timestamp, current_timestamp, 568, 29, 'FX37', ' - FX37'),
(current_timestamp, current_timestamp, 569, 29, 'FX45', ' - FX45'),
(current_timestamp, current_timestamp, 570, 29, 'FX50', ' - FX50'),
(current_timestamp, current_timestamp, 571, 29, 'G_MODELS', 'G Models (4)'),
(current_timestamp, current_timestamp, 572, 29, 'G20', ' - G20'),
(current_timestamp, current_timestamp, 573, 29, 'G25', ' - G25'),
(current_timestamp, current_timestamp, 574, 29, 'G35', ' - G35'),
(current_timestamp, current_timestamp, 575, 29, 'G37', ' - G37'),
(current_timestamp, current_timestamp, 576, 29, 'I_MODELS', 'I Models (2)'),
(current_timestamp, current_timestamp, 577, 29, 'I30', ' - I30'),
(current_timestamp, current_timestamp, 578, 29, 'I35', ' - I35'),
(current_timestamp, current_timestamp, 579, 29, 'J_MODELS', 'J Models (1)'),
(current_timestamp, current_timestamp, 580, 29, 'J30', ' - J30'),
(current_timestamp, current_timestamp, 581, 29, 'JX_MODELS', 'JX Models (1)'),
(current_timestamp, current_timestamp, 582, 29, 'JX35', ' - JX35'),
(current_timestamp, current_timestamp, 583, 29, 'M_MODELS', 'M Models (6)'),
(current_timestamp, current_timestamp, 584, 29, 'M30', ' - M30'),
(current_timestamp, current_timestamp, 585, 29, 'M35', ' - M35'),
(current_timestamp, current_timestamp, 586, 29, 'M35HYBRID', ' - M35h'),
(current_timestamp, current_timestamp, 587, 29, 'M37', ' - M37'),
(current_timestamp, current_timestamp, 588, 29, 'M45', ' - M45'),
(current_timestamp, current_timestamp, 589, 29, 'M56', ' - M56'),
(current_timestamp, current_timestamp, 590, 29, 'Q_MODELS', 'Q Models (1)'),
(current_timestamp, current_timestamp, 591, 29, 'Q45', ' - Q45'),
(current_timestamp, current_timestamp, 592, 29, 'QX_MODELS', 'QX Models (2)'),
(current_timestamp, current_timestamp, 593, 29, 'QX4', ' - QX4'),
(current_timestamp, current_timestamp, 594, 29, 'QX56', ' - QX56'),
(current_timestamp, current_timestamp, 595, 29, 'INFOTH', 'Other Infiniti Models'),
(current_timestamp, current_timestamp, 596, 30, 'AMIGO', 'Amigo'),
(current_timestamp, current_timestamp, 597, 30, 'ASCENDER', 'Ascender'),
(current_timestamp, current_timestamp, 598, 30, 'AXIOM', 'Axiom'),
(current_timestamp, current_timestamp, 599, 30, 'HOMBRE', 'Hombre'),
(current_timestamp, current_timestamp, 600, 30, 'I280', 'i-280'),
(current_timestamp, current_timestamp, 601, 30, 'I290', 'i-290'),
(current_timestamp, current_timestamp, 602, 30, 'I350', 'i-350'),
(current_timestamp, current_timestamp, 603, 30, 'I370', 'i-370'),
(current_timestamp, current_timestamp, 604, 30, 'ISUMARK', 'I-Mark'),
(current_timestamp, current_timestamp, 605, 30, 'ISUIMP', 'Impulse'),
(current_timestamp, current_timestamp, 606, 30, 'OASIS', 'Oasis'),
(current_timestamp, current_timestamp, 607, 30, 'ISUPU', 'Pickup'),
(current_timestamp, current_timestamp, 608, 30, 'RODEO', 'Rodeo'),
(current_timestamp, current_timestamp, 609, 30, 'STYLUS', 'Stylus'),
(current_timestamp, current_timestamp, 610, 30, 'TROOP', 'Trooper'),
(current_timestamp, current_timestamp, 611, 30, 'TRP2', 'Trooper II'),
(current_timestamp, current_timestamp, 612, 30, 'VEHICROSS', 'VehiCROSS'),
(current_timestamp, current_timestamp, 613, 30, 'ISUOTH', 'Other Isuzu Models'),
(current_timestamp, current_timestamp, 614, 31, 'STYPE', 'S-Type'),
(current_timestamp, current_timestamp, 615, 31, 'XTYPE', 'X-Type'),
(current_timestamp, current_timestamp, 616, 31, 'XF', 'XF'),
(current_timestamp, current_timestamp, 617, 31, 'XJ_SERIES', 'XJ Series (10)'),
(current_timestamp, current_timestamp, 618, 31, 'JAGXJ12', ' - XJ12'),
(current_timestamp, current_timestamp, 619, 31, 'JAGXJ6', ' - XJ6'),
(current_timestamp, current_timestamp, 620, 31, 'JAGXJR', ' - XJR'),
(current_timestamp, current_timestamp, 621, 31, 'JAGXJRS', ' - XJR-S'),
(current_timestamp, current_timestamp, 622, 31, 'JAGXJS', ' - XJS'),
(current_timestamp, current_timestamp, 623, 31, 'VANDEN', ' - XJ Vanden Plas'),
(current_timestamp, current_timestamp, 624, 31, 'XJ', ' - XJ'),
(current_timestamp, current_timestamp, 625, 31, 'XJ8', ' - XJ8'),
(current_timestamp, current_timestamp, 626, 31, 'XJ8L', ' - XJ8 L'),
(current_timestamp, current_timestamp, 627, 31, 'XJSPORT', ' - XJ Sport'),
(current_timestamp, current_timestamp, 628, 31, 'XK_SERIES', 'XK Series (3)'),
(current_timestamp, current_timestamp, 629, 31, 'JAGXK8', ' - XK8'),
(current_timestamp, current_timestamp, 630, 31, 'XK', ' - XK'),
(current_timestamp, current_timestamp, 631, 31, 'XKR', ' - XKR'),
(current_timestamp, current_timestamp, 632, 31, 'JAGOTH', 'Other Jaguar Models'),
(current_timestamp, current_timestamp, 633, 32, 'CHER', 'Cherokee'),
(current_timestamp, current_timestamp, 634, 32, 'JEEPCJ', 'CJ'),
(current_timestamp, current_timestamp, 635, 32, 'COMANC', 'Comanche'),
(current_timestamp, current_timestamp, 636, 32, 'COMMANDER', 'Commander'),
(current_timestamp, current_timestamp, 637, 32, 'COMPASS', 'Compass'),
(current_timestamp, current_timestamp, 638, 32, 'JEEPGRAND', 'Grand Cherokee'),
(current_timestamp, current_timestamp, 639, 32, 'GRWAG', 'Grand Wagoneer'),
(current_timestamp, current_timestamp, 640, 32, 'LIBERTY', 'Liberty'),
(current_timestamp, current_timestamp, 641, 32, 'PATRIOT', 'Patriot'),
(current_timestamp, current_timestamp, 642, 32, 'JEEPPU', 'Pickup'),
(current_timestamp, current_timestamp, 643, 32, 'SCRAMBLE', 'Scrambler'),
(current_timestamp, current_timestamp, 644, 32, 'WAGONE', 'Wagoneer'),
(current_timestamp, current_timestamp, 645, 32, 'WRANGLER', 'Wrangler'),
(current_timestamp, current_timestamp, 646, 32, 'JEOTH', 'Other Jeep Models'),
(current_timestamp, current_timestamp, 647, 33, 'AMANTI', 'Amanti'),
(current_timestamp, current_timestamp, 648, 33, 'BORREGO', 'Borrego'),
(current_timestamp, current_timestamp, 649, 33, 'FORTE', 'Forte'),
(current_timestamp, current_timestamp, 650, 33, 'FORTEKOUP', 'Forte Koup'),
(current_timestamp, current_timestamp, 651, 33, 'OPTIMA', 'Optima'),
(current_timestamp, current_timestamp, 652, 33, 'RIO', 'Rio'),
(current_timestamp, current_timestamp, 653, 33, 'RIO5', 'Rio5'),
(current_timestamp, current_timestamp, 654, 33, 'RONDO', 'Rondo'),
(current_timestamp, current_timestamp, 655, 33, 'SEDONA', 'Sedona'),
(current_timestamp, current_timestamp, 656, 33, 'SEPHIA', 'Sephia'),
(current_timestamp, current_timestamp, 657, 33, 'SORENTO', 'Sorento'),
(current_timestamp, current_timestamp, 658, 33, 'SOUL', 'Soul'),
(current_timestamp, current_timestamp, 659, 33, 'SPECTRA', 'Spectra'),
(current_timestamp, current_timestamp, 660, 33, 'SPECTRA5', 'Spectra5'),
(current_timestamp, current_timestamp, 661, 33, 'SPORTA', 'Sportage'),
(current_timestamp, current_timestamp, 662, 33, 'KIAOTH', 'Other Kia Models'),
(current_timestamp, current_timestamp, 663, 34, 'AVENT', 'Aventador'),
(current_timestamp, current_timestamp, 664, 34, 'COUNT', 'Countach'),
(current_timestamp, current_timestamp, 665, 34, 'DIABLO', 'Diablo'),
(current_timestamp, current_timestamp, 666, 34, 'GALLARDO', 'Gallardo'),
(current_timestamp, current_timestamp, 667, 34, 'JALPA', 'Jalpa'),
(current_timestamp, current_timestamp, 668, 34, 'LM002', 'LM002'),
(current_timestamp, current_timestamp, 669, 34, 'MURCIELAGO', 'Murcielago'),
(current_timestamp, current_timestamp, 670, 34, 'UNAVAILLAM', 'Other Lamborghini Models'),
(current_timestamp, current_timestamp, 671, 35, 'BETA', 'Beta'),
(current_timestamp, current_timestamp, 672, 35, 'ZAGATO', 'Zagato'),
(current_timestamp, current_timestamp, 673, 35, 'UNAVAILLAN', 'Other Lancia Models'),
(current_timestamp, current_timestamp, 674, 36, 'DEFEND', 'Defender'),
(current_timestamp, current_timestamp, 675, 36, 'DISCOV', 'Discovery'),
(current_timestamp, current_timestamp, 676, 36, 'FRELNDR', 'Freelander'),
(current_timestamp, current_timestamp, 677, 36, 'LR2', 'LR2'),
(current_timestamp, current_timestamp, 678, 36, 'LR3', 'LR3'),
(current_timestamp, current_timestamp, 679, 36, 'LR4', 'LR4'),
(current_timestamp, current_timestamp, 680, 36, 'RANGE', 'Range Rover'),
(current_timestamp, current_timestamp, 681, 36, 'EVOQUE', 'Range Rover Evoque'),
(current_timestamp, current_timestamp, 682, 36, 'RANGESPORT', 'Range Rover Sport'),
(current_timestamp, current_timestamp, 683, 36, 'ROVOTH', 'Other Land Rover Models'),
(current_timestamp, current_timestamp, 684, 37, 'CT_MODELS', 'CT Models (1)'),
(current_timestamp, current_timestamp, 685, 37, 'CT200H', ' - CT 200h'),
(current_timestamp, current_timestamp, 686, 37, 'ES_MODELS', 'ES Models (5)'),
(current_timestamp, current_timestamp, 687, 37, 'ES250', ' - ES 250'),
(current_timestamp, current_timestamp, 688, 37, 'ES300', ' - ES 300'),
(current_timestamp, current_timestamp, 689, 37, 'ES300H', ' - ES 300h'),
(current_timestamp, current_timestamp, 690, 37, 'ES330', ' - ES 330'),
(current_timestamp, current_timestamp, 691, 37, 'ES350', ' - ES 350'),
(current_timestamp, current_timestamp, 692, 37, 'GS_MODELS', 'GS Models (6)'),
(current_timestamp, current_timestamp, 693, 37, 'GS300', ' - GS 300'),
(current_timestamp, current_timestamp, 694, 37, 'GS350', ' - GS 350'),
(current_timestamp, current_timestamp, 695, 37, 'GS400', ' - GS 400'),
(current_timestamp, current_timestamp, 696, 37, 'GS430', ' - GS 430'),
(current_timestamp, current_timestamp, 697, 37, 'GS450H', ' - GS 450h'),
(current_timestamp, current_timestamp, 698, 37, 'GS460', ' - GS 460'),
(current_timestamp, current_timestamp, 699, 37, 'GX_MODELS', 'GX Models (2)'),
(current_timestamp, current_timestamp, 700, 37, 'GX460', ' - GX 460'),
(current_timestamp, current_timestamp, 701, 37, 'GX470', ' - GX 470'),
(current_timestamp, current_timestamp, 702, 37, 'HS_MODELS', 'HS Models (1)'),
(current_timestamp, current_timestamp, 703, 37, 'HS250H', ' - HS 250h'),
(current_timestamp, current_timestamp, 704, 37, 'IS_MODELS', 'IS Models (6)'),
(current_timestamp, current_timestamp, 705, 37, 'IS250', ' - IS 250'),
(current_timestamp, current_timestamp, 706, 37, 'IS250C', ' - IS 250C'),
(current_timestamp, current_timestamp, 707, 37, 'IS300', ' - IS 300'),
(current_timestamp, current_timestamp, 708, 37, 'IS350', ' - IS 350'),
(current_timestamp, current_timestamp, 709, 37, 'IS350C', ' - IS 350C'),
(current_timestamp, current_timestamp, 710, 37, 'ISF', ' - IS F'),
(current_timestamp, current_timestamp, 711, 37, 'LEXLFA', 'LFA'),
(current_timestamp, current_timestamp, 712, 37, 'LS_MODELS', 'LS Models (4)'),
(current_timestamp, current_timestamp, 713, 37, 'LS400', ' - LS 400'),
(current_timestamp, current_timestamp, 714, 37, 'LS430', ' - LS 430'),
(current_timestamp, current_timestamp, 715, 37, 'LS460', ' - LS 460'),
(current_timestamp, current_timestamp, 716, 37, 'LS600H', ' - LS 600h'),
(current_timestamp, current_timestamp, 717, 37, 'LX_MODELS', 'LX Models (3)'),
(current_timestamp, current_timestamp, 718, 37, 'LX450', ' - LX 450'),
(current_timestamp, current_timestamp, 719, 37, 'LX470', ' - LX 470'),
(current_timestamp, current_timestamp, 720, 37, 'LX570', ' - LX 570'),
(current_timestamp, current_timestamp, 721, 37, 'RX_MODELS', 'RX Models (5)'),
(current_timestamp, current_timestamp, 722, 37, 'RX300', ' - RX 300'),
(current_timestamp, current_timestamp, 723, 37, 'RX330', ' - RX 330'),
(current_timestamp, current_timestamp, 724, 37, 'RX350', ' - RX 350'),
(current_timestamp, current_timestamp, 725, 37, 'RX400H', ' - RX 400h'),
(current_timestamp, current_timestamp, 726, 37, 'RX450H', ' - RX 450h'),
(current_timestamp, current_timestamp, 727, 37, 'SC_MODELS', 'SC Models (3)'),
(current_timestamp, current_timestamp, 728, 37, 'SC300', ' - SC 300'),
(current_timestamp, current_timestamp, 729, 37, 'SC400', ' - SC 400'),
(current_timestamp, current_timestamp, 730, 37, 'SC430', ' - SC 430'),
(current_timestamp, current_timestamp, 731, 37, 'LEXOTH', 'Other Lexus Models'),
(current_timestamp, current_timestamp, 732, 38, 'AVIATOR', 'Aviator'),
(current_timestamp, current_timestamp, 733, 38, 'BLKWOOD', 'Blackwood'),
(current_timestamp, current_timestamp, 734, 38, 'CONT', 'Continental'),
(current_timestamp, current_timestamp, 735, 38, 'LSLINCOLN', 'LS'),
(current_timestamp, current_timestamp, 736, 38, 'MARKLT', 'Mark LT'),
(current_timestamp, current_timestamp, 737, 38, 'MARK6', 'Mark VI'),
(current_timestamp, current_timestamp, 738, 38, 'MARK7', 'Mark VII'),
(current_timestamp, current_timestamp, 739, 38, 'MARK8', 'Mark VIII'),
(current_timestamp, current_timestamp, 740, 38, 'MKS', 'MKS'),
(current_timestamp, current_timestamp, 741, 38, 'MKT', 'MKT'),
(current_timestamp, current_timestamp, 742, 38, 'MKX', 'MKX'),
(current_timestamp, current_timestamp, 743, 38, 'MKZ', 'MKZ'),
(current_timestamp, current_timestamp, 744, 38, 'NAVIGA', 'Navigator'),
(current_timestamp, current_timestamp, 745, 38, 'NAVIGAL', 'Navigator L'),
(current_timestamp, current_timestamp, 746, 38, 'LINCTC', 'Town Car'),
(current_timestamp, current_timestamp, 747, 38, 'ZEPHYR', 'Zephyr'),
(current_timestamp, current_timestamp, 748, 38, 'LINOTH', 'Other Lincoln Models'),
(current_timestamp, current_timestamp, 749, 39, 'ELAN', 'Elan'),
(current_timestamp, current_timestamp, 750, 39, 'LOTELISE', 'Elise'),
(current_timestamp, current_timestamp, 751, 39, 'ESPRIT', 'Esprit'),
(current_timestamp, current_timestamp, 752, 39, 'EVORA', 'Evora'),
(current_timestamp, current_timestamp, 753, 39, 'EXIGE', 'Exige'),
(current_timestamp, current_timestamp, 754, 39, 'UNAVAILLOT', 'Other Lotus Models'),
(current_timestamp, current_timestamp, 755, 40, '430', '430'),
(current_timestamp, current_timestamp, 756, 40, 'BITRBO', 'Biturbo'),
(current_timestamp, current_timestamp, 757, 40, 'COUPEMAS', 'Coupe'),
(current_timestamp, current_timestamp, 758, 40, 'GRANSPORT', 'GranSport'),
(current_timestamp, current_timestamp, 759, 40, 'GRANTURISM', 'GranTurismo'),
(current_timestamp, current_timestamp, 760, 40, 'QP', 'Quattroporte'),
(current_timestamp, current_timestamp, 761, 40, 'SPYDER', 'Spyder'),
(current_timestamp, current_timestamp, 762, 40, 'UNAVAILMAS', 'Other Maserati Models'),
(current_timestamp, current_timestamp, 763, 41, '57MAYBACH', '57'),
(current_timestamp, current_timestamp, 764, 41, '62MAYBACH', '62'),
(current_timestamp, current_timestamp, 765, 41, 'UNAVAILMAY', 'Other Maybach Models'),
(current_timestamp, current_timestamp, 766, 42, 'MAZDA323', '323'),
(current_timestamp, current_timestamp, 767, 42, 'MAZDA626', '626'),
(current_timestamp, current_timestamp, 768, 42, '929', '929'),
(current_timestamp, current_timestamp, 769, 42, 'B-SERIES', 'B-Series Pickup'),
(current_timestamp, current_timestamp, 770, 42, 'CX-5', 'CX-5'),
(current_timestamp, current_timestamp, 771, 42, 'CX-7', 'CX-7'),
(current_timestamp, current_timestamp, 772, 42, 'CX-9', 'CX-9'),
(current_timestamp, current_timestamp, 773, 42, 'GLC', 'GLC'),
(current_timestamp, current_timestamp, 774, 42, 'MAZDA2', 'MAZDA2'),
(current_timestamp, current_timestamp, 775, 42, 'MAZDA3', 'MAZDA3'),
(current_timestamp, current_timestamp, 776, 42, 'MAZDA5', 'MAZDA5'),
(current_timestamp, current_timestamp, 777, 42, 'MAZDA6', 'MAZDA6'),
(current_timestamp, current_timestamp, 778, 42, 'MAZDASPD3', 'MAZDASPEED3'),
(current_timestamp, current_timestamp, 779, 42, 'MAZDASPD6', 'MAZDASPEED6'),
(current_timestamp, current_timestamp, 780, 42, 'MIATA', 'Miata MX5'),
(current_timestamp, current_timestamp, 781, 42, 'MILL', 'Millenia'),
(current_timestamp, current_timestamp, 782, 42, 'MPV', 'MPV'),
(current_timestamp, current_timestamp, 783, 42, 'MX3', 'MX3'),
(current_timestamp, current_timestamp, 784, 42, 'MX6', 'MX6'),
(current_timestamp, current_timestamp, 785, 42, 'NAVAJO', 'Navajo'),
(current_timestamp, current_timestamp, 786, 42, 'PROTE', 'Protege'),
(current_timestamp, current_timestamp, 787, 42, 'PROTE5', 'Protege5'),
(current_timestamp, current_timestamp, 788, 42, 'RX7', 'RX-7'),
(current_timestamp, current_timestamp, 789, 42, 'RX8', 'RX-8'),
(current_timestamp, current_timestamp, 790, 42, 'TRIBUTE', 'Tribute'),
(current_timestamp, current_timestamp, 791, 42, 'MAZOTH', 'Other Mazda Models'),
(current_timestamp, current_timestamp, 792, 43, 'MP4', 'MP4-12C'),
(current_timestamp, current_timestamp, 793, 44, '190_CLASS', '190 Class (2)'),
(current_timestamp, current_timestamp, 794, 44, '190D', ' - 190D'),
(current_timestamp, current_timestamp, 795, 44, '190E', ' - 190E'),
(current_timestamp, current_timestamp, 796, 44, '240_CLASS', '240 Class (1)'),
(current_timestamp, current_timestamp, 797, 44, '240D', ' - 240D'),
(current_timestamp, current_timestamp, 798, 44, '300_CLASS_E_CLASS', '300 Class / E Class (6)'),
(current_timestamp, current_timestamp, 799, 44, '300CD', ' - 300CD'),
(current_timestamp, current_timestamp, 800, 44, '300CE', ' - 300CE'),
(current_timestamp, current_timestamp, 801, 44, '300D', ' - 300D'),
(current_timestamp, current_timestamp, 802, 44, '300E', ' - 300E'),
(current_timestamp, current_timestamp, 803, 44, '300TD', ' - 300TD'),
(current_timestamp, current_timestamp, 804, 44, '300TE', ' - 300TE'),
(current_timestamp, current_timestamp, 805, 44, 'C_CLASS', 'C Class (13)'),
(current_timestamp, current_timestamp, 806, 44, 'C220', ' - C220'),
(current_timestamp, current_timestamp, 807, 44, 'C230', ' - C230'),
(current_timestamp, current_timestamp, 808, 44, 'C240', ' - C240'),
(current_timestamp, current_timestamp, 809, 44, 'C250', ' - C250'),
(current_timestamp, current_timestamp, 810, 44, 'C280', ' - C280'),
(current_timestamp, current_timestamp, 811, 44, 'C300', ' - C300'),
(current_timestamp, current_timestamp, 812, 44, 'C320', ' - C320'),
(current_timestamp, current_timestamp, 813, 44, 'C32AMG', ' - C32 AMG'),
(current_timestamp, current_timestamp, 814, 44, 'C350', ' - C350'),
(current_timestamp, current_timestamp, 815, 44, 'C36AMG', ' - C36 AMG'),
(current_timestamp, current_timestamp, 816, 44, 'C43AMG', ' - C43 AMG'),
(current_timestamp, current_timestamp, 817, 44, 'C55AMG', ' - C55 AMG'),
(current_timestamp, current_timestamp, 818, 44, 'C63AMG', ' - C63 AMG'),
(current_timestamp, current_timestamp, 819, 44, 'CL_CLASS', 'CL Class (6)'),
(current_timestamp, current_timestamp, 820, 44, 'CL500', ' - CL500'),
(current_timestamp, current_timestamp, 821, 44, 'CL550', ' - CL550'),
(current_timestamp, current_timestamp, 822, 44, 'CL55AMG', ' - CL55 AMG'),
(current_timestamp, current_timestamp, 823, 44, 'CL600', ' - CL600'),
(current_timestamp, current_timestamp, 824, 44, 'CL63AMG', ' - CL63 AMG'),
(current_timestamp, current_timestamp, 825, 44, 'CL65AMG', ' - CL65 AMG'),
(current_timestamp, current_timestamp, 826, 44, 'CLK_CLASS', 'CLK Class (7)'),
(current_timestamp, current_timestamp, 827, 44, 'CLK320', ' - CLK320'),
(current_timestamp, current_timestamp, 828, 44, 'CLK350', ' - CLK350'),
(current_timestamp, current_timestamp, 829, 44, 'CLK430', ' - CLK430'),
(current_timestamp, current_timestamp, 830, 44, 'CLK500', ' - CLK500'),
(current_timestamp, current_timestamp, 831, 44, 'CLK550', ' - CLK550'),
(current_timestamp, current_timestamp, 832, 44, 'CLK55AMG', ' - CLK55 AMG'),
(current_timestamp, current_timestamp, 833, 44, 'CLK63AMG', ' - CLK63 AMG'),
(current_timestamp, current_timestamp, 834, 44, 'CLS_CLASS', 'CLS Class (4)'),
(current_timestamp, current_timestamp, 835, 44, 'CLS500', ' - CLS500'),
(current_timestamp, current_timestamp, 836, 44, 'CLS550', ' - CLS550'),
(current_timestamp, current_timestamp, 837, 44, 'CLS55AMG', ' - CLS55 AMG'),
(current_timestamp, current_timestamp, 838, 44, 'CLS63AMG', ' - CLS63 AMG'),
(current_timestamp, current_timestamp, 839, 44, 'E_CLASS', 'E Class (18)'),
(current_timestamp, current_timestamp, 840, 44, '260E', ' - 260E'),
(current_timestamp, current_timestamp, 841, 44, '280CE', ' - 280CE'),
(current_timestamp, current_timestamp, 842, 44, '280E', ' - 280E'),
(current_timestamp, current_timestamp, 843, 44, '400E', ' - 400E'),
(current_timestamp, current_timestamp, 844, 44, '500E', ' - 500E'),
(current_timestamp, current_timestamp, 845, 44, 'E300', ' - E300'),
(current_timestamp, current_timestamp, 846, 44, 'E320', ' - E320'),
(current_timestamp, current_timestamp, 847, 44, 'E320BLUE', ' - E320 Bluetec'),
(current_timestamp, current_timestamp, 848, 44, 'E320CDI', ' - E320 CDI'),
(current_timestamp, current_timestamp, 849, 44, 'E350', ' - E350'),
(current_timestamp, current_timestamp, 850, 44, 'E350BLUE', ' - E350 Bluetec'),
(current_timestamp, current_timestamp, 851, 44, 'E400', ' - E400 Hybrid'),
(current_timestamp, current_timestamp, 852, 44, 'E420', ' - E420'),
(current_timestamp, current_timestamp, 853, 44, 'E430', ' - E430'),
(current_timestamp, current_timestamp, 854, 44, 'E500', ' - E500'),
(current_timestamp, current_timestamp, 855, 44, 'E550', ' - E550'),
(current_timestamp, current_timestamp, 856, 44, 'E55AMG', ' - E55 AMG'),
(current_timestamp, current_timestamp, 857, 44, 'E63AMG', ' - E63 AMG'),
(current_timestamp, current_timestamp, 858, 44, 'G_CLASS', 'G Class (4)'),
(current_timestamp, current_timestamp, 859, 44, 'G500', ' - G500'),
(current_timestamp, current_timestamp, 860, 44, 'G550', ' - G550'),
(current_timestamp, current_timestamp, 861, 44, 'G55AMG', ' - G55 AMG'),
(current_timestamp, current_timestamp, 862, 44, 'G63AMG', ' - G63 AMG'),
(current_timestamp, current_timestamp, 863, 44, 'GL_CLASS', 'GL Class (5)'),
(current_timestamp, current_timestamp, 864, 44, 'GL320BLUE', ' - GL320 Bluetec'),
(current_timestamp, current_timestamp, 865, 44, 'GL320CDI', ' - GL320 CDI'),
(current_timestamp, current_timestamp, 866, 44, 'GL350BLUE', ' - GL350 Bluetec'),
(current_timestamp, current_timestamp, 867, 44, 'GL450', ' - GL450'),
(current_timestamp, current_timestamp, 868, 44, 'GL550', ' - GL550'),
(current_timestamp, current_timestamp, 869, 44, 'GLK_CLASS', 'GLK Class (1)'),
(current_timestamp, current_timestamp, 870, 44, 'GLK350', ' - GLK350'),
(current_timestamp, current_timestamp, 871, 44, 'M_CLASS', 'M Class (11)'),
(current_timestamp, current_timestamp, 872, 44, 'ML320', ' - ML320'),
(current_timestamp, current_timestamp, 873, 44, 'ML320BLUE', ' - ML320 Bluetec'),
(current_timestamp, current_timestamp, 874, 44, 'ML320CDI', ' - ML320 CDI'),
(current_timestamp, current_timestamp, 875, 44, 'ML350', ' - ML350'),
(current_timestamp, current_timestamp, 876, 44, 'ML350BLUE', ' - ML350 Bluetec'),
(current_timestamp, current_timestamp, 877, 44, 'ML430', ' - ML430'),
(current_timestamp, current_timestamp, 878, 44, 'ML450HY', ' - ML450 Hybrid'),
(current_timestamp, current_timestamp, 879, 44, 'ML500', ' - ML500'),
(current_timestamp, current_timestamp, 880, 44, 'ML550', ' - ML550'),
(current_timestamp, current_timestamp, 881, 44, 'ML55AMG', ' - ML55 AMG'),
(current_timestamp, current_timestamp, 882, 44, 'ML63AMG', ' - ML63 AMG'),
(current_timestamp, current_timestamp, 883, 44, 'R_CLASS', 'R Class (6)'),
(current_timestamp, current_timestamp, 884, 44, 'R320BLUE', ' - R320 Bluetec'),
(current_timestamp, current_timestamp, 885, 44, 'R320CDI', ' - R320 CDI'),
(current_timestamp, current_timestamp, 886, 44, 'R350', ' - R350'),
(current_timestamp, current_timestamp, 887, 44, 'R350BLUE', ' - R350 Bluetec'),
(current_timestamp, current_timestamp, 888, 44, 'R500', ' - R500'),
(current_timestamp, current_timestamp, 889, 44, 'R63AMG', ' - R63 AMG'),
(current_timestamp, current_timestamp, 890, 44, 'S_CLASS', 'S Class (30)'),
(current_timestamp, current_timestamp, 891, 44, '300SD', ' - 300SD'),
(current_timestamp, current_timestamp, 892, 44, '300SDL', ' - 300SDL'),
(current_timestamp, current_timestamp, 893, 44, '300SE', ' - 300SE'),
(current_timestamp, current_timestamp, 894, 44, '300SEL', ' - 300SEL'),
(current_timestamp, current_timestamp, 895, 44, '350SD', ' - 350SD'),
(current_timestamp, current_timestamp, 896, 44, '350SDL', ' - 350SDL'),
(current_timestamp, current_timestamp, 897, 44, '380SE', ' - 380SE'),
(current_timestamp, current_timestamp, 898, 44, '380SEC', ' - 380SEC'),
(current_timestamp, current_timestamp, 899, 44, '380SEL', ' - 380SEL'),
(current_timestamp, current_timestamp, 900, 44, '400SE', ' - 400SE'),
(current_timestamp, current_timestamp, 901, 44, '400SEL', ' - 400SEL'),
(current_timestamp, current_timestamp, 902, 44, '420SEL', ' - 420SEL'),
(current_timestamp, current_timestamp, 903, 44, '500SEC', ' - 500SEC'),
(current_timestamp, current_timestamp, 904, 44, '500SEL', ' - 500SEL'),
(current_timestamp, current_timestamp, 905, 44, '560SEC', ' - 560SEC'),
(current_timestamp, current_timestamp, 906, 44, '560SEL', ' - 560SEL'),
(current_timestamp, current_timestamp, 907, 44, '600SEC', ' - 600SEC'),
(current_timestamp, current_timestamp, 908, 44, '600SEL', ' - 600SEL'),
(current_timestamp, current_timestamp, 909, 44, 'S320', ' - S320'),
(current_timestamp, current_timestamp, 910, 44, 'S350', ' - S350'),
(current_timestamp, current_timestamp, 911, 44, 'S350BLUE', ' - S350 Bluetec'),
(current_timestamp, current_timestamp, 912, 44, 'S400HY', ' - S400 Hybrid'),
(current_timestamp, current_timestamp, 913, 44, 'S420', ' - S420'),
(current_timestamp, current_timestamp, 914, 44, 'S430', ' - S430'),
(current_timestamp, current_timestamp, 915, 44, 'S500', ' - S500'),
(current_timestamp, current_timestamp, 916, 44, 'S550', ' - S550'),
(current_timestamp, current_timestamp, 917, 44, 'S55AMG', ' - S55 AMG'),
(current_timestamp, current_timestamp, 918, 44, 'S600', ' - S600'),
(current_timestamp, current_timestamp, 919, 44, 'S63AMG', ' - S63 AMG'),
(current_timestamp, current_timestamp, 920, 44, 'S65AMG', ' - S65 AMG'),
(current_timestamp, current_timestamp, 921, 44, 'SL_CLASS', 'SL Class (13)'),
(current_timestamp, current_timestamp, 922, 44, '300SL', ' - 300SL'),
(current_timestamp, current_timestamp, 923, 44, '380SL', ' - 380SL'),
(current_timestamp, current_timestamp, 924, 44, '380SLC', ' - 380SLC'),
(current_timestamp, current_timestamp, 925, 44, '500SL', ' - 500SL'),
(current_timestamp, current_timestamp, 926, 44, '560SL', ' - 560SL'),
(current_timestamp, current_timestamp, 927, 44, '600SL', ' - 600SL'),
(current_timestamp, current_timestamp, 928, 44, 'SL320', ' - SL320'),
(current_timestamp, current_timestamp, 929, 44, 'SL500', ' - SL500'),
(current_timestamp, current_timestamp, 930, 44, 'SL550', ' - SL550'),
(current_timestamp, current_timestamp, 931, 44, 'SL55AMG', ' - SL55 AMG'),
(current_timestamp, current_timestamp, 932, 44, 'SL600', ' - SL600'),
(current_timestamp, current_timestamp, 933, 44, 'SL63AMG', ' - SL63 AMG'),
(current_timestamp, current_timestamp, 934, 44, 'SL65AMG', ' - SL65 AMG'),
(current_timestamp, current_timestamp, 935, 44, 'SLK_CLASS', 'SLK Class (8)'),
(current_timestamp, current_timestamp, 936, 44, 'SLK230', ' - SLK230'),
(current_timestamp, current_timestamp, 937, 44, 'SLK250', ' - SLK250'),
(current_timestamp, current_timestamp, 938, 44, 'SLK280', ' - SLK280'),
(current_timestamp, current_timestamp, 939, 44, 'SLK300', ' - SLK300'),
(current_timestamp, current_timestamp, 940, 44, 'SLK320', ' - SLK320'),
(current_timestamp, current_timestamp, 941, 44, 'SLK32AMG', ' - SLK32 AMG'),
(current_timestamp, current_timestamp, 942, 44, 'SLK350', ' - SLK350'),
(current_timestamp, current_timestamp, 943, 44, 'SLK55AMG', ' - SLK55 AMG'),
(current_timestamp, current_timestamp, 944, 44, 'SLR_CLASS', 'SLR Class (1)'),
(current_timestamp, current_timestamp, 945, 44, 'SLR', ' - SLR'),
(current_timestamp, current_timestamp, 946, 44, 'SLS_CLASS', 'SLS Class (1)'),
(current_timestamp, current_timestamp, 947, 44, 'SLSAMG', ' - SLS AMG'),
(current_timestamp, current_timestamp, 948, 44, 'SPRINTER_CLASS', 'Sprinter Class (1)'),
(current_timestamp, current_timestamp, 949, 44, 'MBSPRINTER', ' - Sprinter'),
(current_timestamp, current_timestamp, 950, 44, 'MBOTH', 'Other Mercedes-Benz Models'),
(current_timestamp, current_timestamp, 951, 45, 'CAPRI', 'Capri'),
(current_timestamp, current_timestamp, 952, 45, 'COUGAR', 'Cougar'),
(current_timestamp, current_timestamp, 953, 45, 'MERCGRAND', 'Grand Marquis'),
(current_timestamp, current_timestamp, 954, 45, 'LYNX', 'Lynx'),
(current_timestamp, current_timestamp, 955, 45, 'MARAUDER', 'Marauder'),
(current_timestamp, current_timestamp, 956, 45, 'MARINER', 'Mariner'),
(current_timestamp, current_timestamp, 957, 45, 'MARQ', 'Marquis'),
(current_timestamp, current_timestamp, 958, 45, 'MILAN', 'Milan'),
(current_timestamp, current_timestamp, 959, 45, 'MONTEGO', 'Montego'),
(current_timestamp, current_timestamp, 960, 45, 'MONTEREY', 'Monterey'),
(current_timestamp, current_timestamp, 961, 45, 'MOUNTA', 'Mountaineer'),
(current_timestamp, current_timestamp, 962, 45, 'MYSTIQ', 'Mystique'),
(current_timestamp, current_timestamp, 963, 45, 'SABLE', 'Sable'),
(current_timestamp, current_timestamp, 964, 45, 'TOPAZ', 'Topaz'),
(current_timestamp, current_timestamp, 965, 45, 'TRACER', 'Tracer'),
(current_timestamp, current_timestamp, 966, 45, 'VILLA', 'Villager'),
(current_timestamp, current_timestamp, 967, 45, 'MERCZEP', 'Zephyr'),
(current_timestamp, current_timestamp, 968, 45, 'MEOTH', 'Other Mercury Models'),
(current_timestamp, current_timestamp, 969, 46, 'SCORP', 'Scorpio'),
(current_timestamp, current_timestamp, 970, 46, 'XR4TI', 'XR4Ti'),
(current_timestamp, current_timestamp, 971, 46, 'MEROTH', 'Other Merkur Models'),
(current_timestamp, current_timestamp, 972, 47, 'COOPRCLUB_MODELS', 'Cooper Clubman Models (2)'),
(current_timestamp, current_timestamp, 973, 47, 'COOPERCLUB', ' - Cooper Clubman'),
(current_timestamp, current_timestamp, 974, 47, 'COOPRCLUBS', ' - Cooper S Clubman'),
(current_timestamp, current_timestamp, 975, 47, 'COOPCOUNTRY_MODELS', 'Cooper Countryman Models (2)'),
(current_timestamp, current_timestamp, 976, 47, 'COUNTRYMAN', ' - Cooper Countryman'),
(current_timestamp, current_timestamp, 977, 47, 'COUNTRYMNS', ' - Cooper S Countryman'),
(current_timestamp, current_timestamp, 978, 47, 'COOPCOUP_MODELS', 'Cooper Coupe Models (2)'),
(current_timestamp, current_timestamp, 979, 47, 'MINICOUPE', ' - Cooper Coupe'),
(current_timestamp, current_timestamp, 980, 47, 'MINISCOUPE', ' - Cooper S Coupe'),
(current_timestamp, current_timestamp, 981, 47, 'COOPER_MODELS', 'Cooper Models (2)'),
(current_timestamp, current_timestamp, 982, 47, 'COOPER', ' - Cooper'),
(current_timestamp, current_timestamp, 983, 47, 'COOPERS', ' - Cooper S'),
(current_timestamp, current_timestamp, 984, 47, 'COOPRROAD_MODELS', 'Cooper Roadster Models (2)'),
(current_timestamp, current_timestamp, 985, 47, 'COOPERROAD', ' - Cooper Roadster'),
(current_timestamp, current_timestamp, 986, 47, 'COOPERSRD', ' - Cooper S Roadster'),
(current_timestamp, current_timestamp, 987, 48, '3000GT', '3000GT'),
(current_timestamp, current_timestamp, 988, 48, 'CORD', 'Cordia'),
(current_timestamp, current_timestamp, 989, 48, 'DIAMAN', 'Diamante'),
(current_timestamp, current_timestamp, 990, 48, 'ECLIP', 'Eclipse'),
(current_timestamp, current_timestamp, 991, 48, 'ENDEAVOR', 'Endeavor'),
(current_timestamp, current_timestamp, 992, 48, 'MITEXP', 'Expo'),
(current_timestamp, current_timestamp, 993, 48, 'GALANT', 'Galant'),
(current_timestamp, current_timestamp, 994, 48, 'MITI', 'i'),
(current_timestamp, current_timestamp, 995, 48, 'LANCERMITS', 'Lancer'),
(current_timestamp, current_timestamp, 996, 48, 'LANCEREVO', 'Lancer Evolution'),
(current_timestamp, current_timestamp, 997, 48, 'MITPU', 'Mighty Max'),
(current_timestamp, current_timestamp, 998, 48, 'MIRAGE', 'Mirage'),
(current_timestamp, current_timestamp, 999, 48, 'MONT', 'Montero'),
(current_timestamp, current_timestamp, 1000, 48, 'MONTSPORT', 'Montero Sport'),
(current_timestamp, current_timestamp, 1001, 48, 'OUTLANDER', 'Outlander'),
(current_timestamp, current_timestamp, 1002, 48, 'OUTLANDSPT', 'Outlander Sport'),
(current_timestamp, current_timestamp, 1003, 48, 'PRECIS', 'Precis'),
(current_timestamp, current_timestamp, 1004, 48, 'RAIDERMITS', 'Raider'),
(current_timestamp, current_timestamp, 1005, 48, 'SIGMA', 'Sigma'),
(current_timestamp, current_timestamp, 1006, 48, 'MITSTAR', 'Starion'),
(current_timestamp, current_timestamp, 1007, 48, 'TRED', 'Tredia'),
(current_timestamp, current_timestamp, 1008, 48, 'MITVAN', 'Van'),
(current_timestamp, current_timestamp, 1009, 48, 'MITOTH', 'Other Mitsubishi Models'),
(current_timestamp, current_timestamp, 1010, 49, 'NIS200SX', '200SX'),
(current_timestamp, current_timestamp, 1011, 49, '240SX', '240SX'),
(current_timestamp, current_timestamp, 1012, 49, '300ZXTURBO', '300ZX'),
(current_timestamp, current_timestamp, 1013, 49, '350Z', '350Z'),
(current_timestamp, current_timestamp, 1014, 49, '370Z', '370Z'),
(current_timestamp, current_timestamp, 1015, 49, 'ALTIMA', 'Altima'),
(current_timestamp, current_timestamp, 1016, 49, 'PATHARMADA', 'Armada'),
(current_timestamp, current_timestamp, 1017, 49, 'AXXESS', 'Axxess'),
(current_timestamp, current_timestamp, 1018, 49, 'CUBE', 'Cube'),
(current_timestamp, current_timestamp, 1019, 49, 'FRONTI', 'Frontier'),
(current_timestamp, current_timestamp, 1020, 49, 'GT-R', 'GT-R'),
(current_timestamp, current_timestamp, 1021, 49, 'JUKE', 'Juke'),
(current_timestamp, current_timestamp, 1022, 49, 'LEAF', 'Leaf'),
(current_timestamp, current_timestamp, 1023, 49, 'MAX', 'Maxima'),
(current_timestamp, current_timestamp, 1024, 49, 'MURANO', 'Murano'),
(current_timestamp, current_timestamp, 1025, 49, 'MURANOCROS', 'Murano CrossCabriolet'),
(current_timestamp, current_timestamp, 1026, 49, 'NV', 'NV'),
(current_timestamp, current_timestamp, 1027, 49, 'NX', 'NX'),
(current_timestamp, current_timestamp, 1028, 49, 'PATH', 'Pathfinder'),
(current_timestamp, current_timestamp, 1029, 49, 'NISPU', 'Pickup'),
(current_timestamp, current_timestamp, 1030, 49, 'PULSAR', 'Pulsar'),
(current_timestamp, current_timestamp, 1031, 49, 'QUEST', 'Quest'),
(current_timestamp, current_timestamp, 1032, 49, 'ROGUE', 'Rogue'),
(current_timestamp, current_timestamp, 1033, 49, 'SENTRA', 'Sentra'),
(current_timestamp, current_timestamp, 1034, 49, 'STANZA', 'Stanza'),
(current_timestamp, current_timestamp, 1035, 49, 'TITAN', 'Titan'),
(current_timestamp, current_timestamp, 1036, 49, 'NISVAN', 'Van'),
(current_timestamp, current_timestamp, 1037, 49, 'VERSA', 'Versa'),
(current_timestamp, current_timestamp, 1038, 49, 'XTERRA', 'Xterra'),
(current_timestamp, current_timestamp, 1039, 49, 'NISSOTH', 'Other Nissan Models'),
(current_timestamp, current_timestamp, 1040, 50, '88', '88'),
(current_timestamp, current_timestamp, 1041, 50, 'ACHIEV', 'Achieva'),
(current_timestamp, current_timestamp, 1042, 50, 'ALERO', 'Alero'),
(current_timestamp, current_timestamp, 1043, 50, 'AURORA', 'Aurora'),
(current_timestamp, current_timestamp, 1044, 50, 'BRAV', 'Bravada'),
(current_timestamp, current_timestamp, 1045, 50, 'CUCR', 'Custom Cruiser'),
(current_timestamp, current_timestamp, 1046, 50, 'OLDCUS', 'Cutlass'),
(current_timestamp, current_timestamp, 1047, 50, 'OLDCALAIS', 'Cutlass Calais'),
(current_timestamp, current_timestamp, 1048, 50, 'CIERA', 'Cutlass Ciera'),
(current_timestamp, current_timestamp, 1049, 50, 'CSUPR', 'Cutlass Supreme'),
(current_timestamp, current_timestamp, 1050, 50, 'OLDSFIR', 'Firenza'),
(current_timestamp, current_timestamp, 1051, 50, 'INTRIG', 'Intrigue'),
(current_timestamp, current_timestamp, 1052, 50, '98', 'Ninety-Eight'),
(current_timestamp, current_timestamp, 1053, 50, 'OMEG', 'Omega'),
(current_timestamp, current_timestamp, 1054, 50, 'REGEN', 'Regency'),
(current_timestamp, current_timestamp, 1055, 50, 'SILHO', 'Silhouette'),
(current_timestamp, current_timestamp, 1056, 50, 'TORO', 'Toronado'),
(current_timestamp, current_timestamp, 1057, 50, 'OLDOTH', 'Other Oldsmobile Models'),
(current_timestamp, current_timestamp, 1058, 51, '405', '405'),
(current_timestamp, current_timestamp, 1059, 51, '504', '504'),
(current_timestamp, current_timestamp, 1060, 51, '505', '505'),
(current_timestamp, current_timestamp, 1061, 51, '604', '604'),
(current_timestamp, current_timestamp, 1062, 51, 'UNAVAILPEU', 'Other Peugeot Models'),
(current_timestamp, current_timestamp, 1063, 52, 'ACC', 'Acclaim'),
(current_timestamp, current_timestamp, 1064, 52, 'ARROW', 'Arrow'),
(current_timestamp, current_timestamp, 1065, 52, 'BREEZE', 'Breeze'),
(current_timestamp, current_timestamp, 1066, 52, 'CARAVE', 'Caravelle'),
(current_timestamp, current_timestamp, 1067, 52, 'CHAMP', 'Champ'),
(current_timestamp, current_timestamp, 1068, 52, 'COLT', 'Colt'),
(current_timestamp, current_timestamp, 1069, 52, 'PLYMCONQ', 'Conquest'),
(current_timestamp, current_timestamp, 1070, 52, 'GRANFURY', 'Gran Fury'),
(current_timestamp, current_timestamp, 1071, 52, 'PLYMGRANV', 'Grand Voyager'),
(current_timestamp, current_timestamp, 1072, 52, 'HORI', 'Horizon'),
(current_timestamp, current_timestamp, 1073, 52, 'LASER', 'Laser'),
(current_timestamp, current_timestamp, 1074, 52, 'NEON', 'Neon'),
(current_timestamp, current_timestamp, 1075, 52, 'PROWLE', 'Prowler'),
(current_timestamp, current_timestamp, 1076, 52, 'RELI', 'Reliant'),
(current_timestamp, current_timestamp, 1077, 52, 'SAPPOROPLY', 'Sapporo'),
(current_timestamp, current_timestamp, 1078, 52, 'SCAMP', 'Scamp'),
(current_timestamp, current_timestamp, 1079, 52, 'SUNDAN', 'Sundance'),
(current_timestamp, current_timestamp, 1080, 52, 'TRAILDUST', 'Trailduster'),
(current_timestamp, current_timestamp, 1081, 52, 'VOYA', 'Voyager'),
(current_timestamp, current_timestamp, 1082, 52, 'PLYOTH', 'Other Plymouth Models'),
(current_timestamp, current_timestamp, 1083, 53, 'T-1000', '1000'),
(current_timestamp, current_timestamp, 1084, 53, '6000', '6000'),
(current_timestamp, current_timestamp, 1085, 53, 'AZTEK', 'Aztek'),
(current_timestamp, current_timestamp, 1086, 53, 'BON', 'Bonneville'),
(current_timestamp, current_timestamp, 1087, 53, 'CATALINA', 'Catalina'),
(current_timestamp, current_timestamp, 1088, 53, 'FIERO', 'Fiero'),
(current_timestamp, current_timestamp, 1089, 53, 'FBIRD', 'Firebird'),
(current_timestamp, current_timestamp, 1090, 53, 'G3', 'G3'),
(current_timestamp, current_timestamp, 1091, 53, 'G5', 'G5'),
(current_timestamp, current_timestamp, 1092, 53, 'G6', 'G6'),
(current_timestamp, current_timestamp, 1093, 53, 'G8', 'G8'),
(current_timestamp, current_timestamp, 1094, 53, 'GRNDAM', 'Grand Am'),
(current_timestamp, current_timestamp, 1095, 53, 'GP', 'Grand Prix'),
(current_timestamp, current_timestamp, 1096, 53, 'GTO', 'GTO'),
(current_timestamp, current_timestamp, 1097, 53, 'J2000', 'J2000'),
(current_timestamp, current_timestamp, 1098, 53, 'LEMANS', 'Le Mans'),
(current_timestamp, current_timestamp, 1099, 53, 'MONTANA', 'Montana'),
(current_timestamp, current_timestamp, 1100, 53, 'PARISI', 'Parisienne'),
(current_timestamp, current_timestamp, 1101, 53, 'PHOENIX', 'Phoenix'),
(current_timestamp, current_timestamp, 1102, 53, 'SAFARIPONT', 'Safari'),
(current_timestamp, current_timestamp, 1103, 53, 'SOLSTICE', 'Solstice'),
(current_timestamp, current_timestamp, 1104, 53, 'SUNBIR', 'Sunbird'),
(current_timestamp, current_timestamp, 1105, 53, 'SUNFIR', 'Sunfire'),
(current_timestamp, current_timestamp, 1106, 53, 'TORRENT', 'Torrent'),
(current_timestamp, current_timestamp, 1107, 53, 'TS', 'Trans Sport'),
(current_timestamp, current_timestamp, 1108, 53, 'VIBE', 'Vibe'),
(current_timestamp, current_timestamp, 1109, 53, 'PONOTH', 'Other Pontiac Models'),
(current_timestamp, current_timestamp, 1110, 54, '911', '911'),
(current_timestamp, current_timestamp, 1111, 54, '924', '924'),
(current_timestamp, current_timestamp, 1112, 54, '928', '928'),
(current_timestamp, current_timestamp, 1113, 54, '944', '944'),
(current_timestamp, current_timestamp, 1114, 54, '968', '968'),
(current_timestamp, current_timestamp, 1115, 54, 'BOXSTE', 'Boxster'),
(current_timestamp, current_timestamp, 1116, 54, 'CARRERAGT', 'Carrera GT'),
(current_timestamp, current_timestamp, 1117, 54, 'CAYENNE', 'Cayenne'),
(current_timestamp, current_timestamp, 1118, 54, 'CAYMAN', 'Cayman'),
(current_timestamp, current_timestamp, 1119, 54, 'PANAMERA', 'Panamera'),
(current_timestamp, current_timestamp, 1120, 54, 'POROTH', 'Other Porsche Models'),
(current_timestamp, current_timestamp, 1121, 55, 'RAM1504WD', '1500'),
(current_timestamp, current_timestamp, 1122, 55, 'RAM25002WD', '2500'),
(current_timestamp, current_timestamp, 1123, 55, 'RAM3502WD', '3500'),
(current_timestamp, current_timestamp, 1124, 55, 'RAM4500', '4500'),
(current_timestamp, current_timestamp, 1125, 56, '18I', '18i'),
(current_timestamp, current_timestamp, 1126, 56, 'FU', 'Fuego'),
(current_timestamp, current_timestamp, 1127, 56, 'LECAR', 'Le Car'),
(current_timestamp, current_timestamp, 1128, 56, 'R18', 'R18'),
(current_timestamp, current_timestamp, 1129, 56, 'RENSPORT', 'Sportwagon'),
(current_timestamp, current_timestamp, 1130, 56, 'UNAVAILREN', 'Other Renault Models'),
(current_timestamp, current_timestamp, 1131, 57, 'CAMAR', 'Camargue'),
(current_timestamp, current_timestamp, 1132, 57, 'CORN', 'Corniche'),
(current_timestamp, current_timestamp, 1133, 57, 'GHOST', 'Ghost'),
(current_timestamp, current_timestamp, 1134, 57, 'PARKWARD', 'Park Ward'),
(current_timestamp, current_timestamp, 1135, 57, 'PHANT', 'Phantom'),
(current_timestamp, current_timestamp, 1136, 57, 'DAWN', 'Silver Dawn'),
(current_timestamp, current_timestamp, 1137, 57, 'SILSERAPH', 'Silver Seraph'),
(current_timestamp, current_timestamp, 1138, 57, 'RRSPIR', 'Silver Spirit'),
(current_timestamp, current_timestamp, 1139, 57, 'SPUR', 'Silver Spur'),
(current_timestamp, current_timestamp, 1140, 57, 'UNAVAILRR', 'Other Rolls-Royce Models'),
(current_timestamp, current_timestamp, 1141, 58, '9-2X', '9-2X'),
(current_timestamp, current_timestamp, 1142, 58, '9-3', '9-3'),
(current_timestamp, current_timestamp, 1143, 58, '9-4X', '9-4X'),
(current_timestamp, current_timestamp, 1144, 58, '9-5', '9-5'),
(current_timestamp, current_timestamp, 1145, 58, '97X', '9-7X'),
(current_timestamp, current_timestamp, 1146, 58, '900', '900'),
(current_timestamp, current_timestamp, 1147, 58, '9000', '9000'),
(current_timestamp, current_timestamp, 1148, 58, 'SAOTH', 'Other Saab Models'),
(current_timestamp, current_timestamp, 1149, 59, 'ASTRA', 'Astra'),
(current_timestamp, current_timestamp, 1150, 59, 'AURA', 'Aura'),
(current_timestamp, current_timestamp, 1151, 59, 'ION', 'ION'),
(current_timestamp, current_timestamp, 1152, 59, 'L_SERIES', 'L Series (3)'),
(current_timestamp, current_timestamp, 1153, 59, 'L100', ' - L100'),
(current_timestamp, current_timestamp, 1154, 59, 'L200', ' - L200'),
(current_timestamp, current_timestamp, 1155, 59, 'L300', ' - L300'),
(current_timestamp, current_timestamp, 1156, 59, 'LSSATURN', 'LS'),
(current_timestamp, current_timestamp, 1157, 59, 'LW_SERIES', 'LW Series (4)'),
(current_timestamp, current_timestamp, 1158, 59, 'LW', ' - LW1'),
(current_timestamp, current_timestamp, 1159, 59, 'LW2', ' - LW2'),
(current_timestamp, current_timestamp, 1160, 59, 'LW200', ' - LW200'),
(current_timestamp, current_timestamp, 1161, 59, 'LW300', ' - LW300'),
(current_timestamp, current_timestamp, 1162, 59, 'OUTLOOK', 'Outlook'),
(current_timestamp, current_timestamp, 1163, 59, 'RELAY', 'Relay'),
(current_timestamp, current_timestamp, 1164, 59, 'SC_SERIES', 'SC Series (2)'),
(current_timestamp, current_timestamp, 1165, 59, 'SC1', ' - SC1'),
(current_timestamp, current_timestamp, 1166, 59, 'SC2', ' - SC2'),
(current_timestamp, current_timestamp, 1167, 59, 'SKY', 'Sky'),
(current_timestamp, current_timestamp, 1168, 59, 'SL_SERIES', 'SL Series (3)'),
(current_timestamp, current_timestamp, 1169, 59, 'SL', ' - SL'),
(current_timestamp, current_timestamp, 1170, 59, 'SL1', ' - SL1'),
(current_timestamp, current_timestamp, 1171, 59, 'SL2', ' - SL2'),
(current_timestamp, current_timestamp, 1172, 59, 'SW_SERIES', 'SW Series (2)'),
(current_timestamp, current_timestamp, 1173, 59, 'SW1', ' - SW1'),
(current_timestamp, current_timestamp, 1174, 59, 'SW2', ' - SW2'),
(current_timestamp, current_timestamp, 1175, 59, 'VUE', 'Vue'),
(current_timestamp, current_timestamp, 1176, 59, 'SATOTH', 'Other Saturn Models'),
(current_timestamp, current_timestamp, 1177, 60, 'SCIFRS', 'FR-S'),
(current_timestamp, current_timestamp, 1178, 60, 'IQ', 'iQ'),
(current_timestamp, current_timestamp, 1179, 60, 'TC', 'tC'),
(current_timestamp, current_timestamp, 1180, 60, 'XA', 'xA'),
(current_timestamp, current_timestamp, 1181, 60, 'XB', 'xB'),
(current_timestamp, current_timestamp, 1182, 60, 'XD', 'xD'),
(current_timestamp, current_timestamp, 1183, 61, 'FORTWO', 'fortwo'),
(current_timestamp, current_timestamp, 1184, 61, 'SMOTH', 'Other smart Models'),
(current_timestamp, current_timestamp, 1185, 62, 'SRTVIPER', 'Viper'),
(current_timestamp, current_timestamp, 1186, 63, '825', '825'),
(current_timestamp, current_timestamp, 1187, 63, '827', '827'),
(current_timestamp, current_timestamp, 1188, 63, 'UNAVAILSTE', 'Other Sterling Models'),
(current_timestamp, current_timestamp, 1189, 64, 'BAJA', 'Baja'),
(current_timestamp, current_timestamp, 1190, 64, 'BRAT', 'Brat'),
(current_timestamp, current_timestamp, 1191, 64, 'SUBBRZ', 'BRZ'),
(current_timestamp, current_timestamp, 1192, 64, 'FOREST', 'Forester'),
(current_timestamp, current_timestamp, 1193, 64, 'IMPREZ', 'Impreza'),
(current_timestamp, current_timestamp, 1194, 64, 'IMPWRX', 'Impreza WRX'),
(current_timestamp, current_timestamp, 1195, 64, 'JUSTY', 'Justy'),
(current_timestamp, current_timestamp, 1196, 64, 'SUBL', 'L Series'),
(current_timestamp, current_timestamp, 1197, 64, 'LEGACY', 'Legacy'),
(current_timestamp, current_timestamp, 1198, 64, 'LOYALE', 'Loyale'),
(current_timestamp, current_timestamp, 1199, 64, 'SUBOUTBK', 'Outback'),
(current_timestamp, current_timestamp, 1200, 64, 'SVX', 'SVX'),
(current_timestamp, current_timestamp, 1201, 64, 'B9TRIBECA', 'Tribeca'),
(current_timestamp, current_timestamp, 1202, 64, 'XT', 'XT'),
(current_timestamp, current_timestamp, 1203, 64, 'XVCRSSTREK', 'XV Crosstrek'),
(current_timestamp, current_timestamp, 1204, 64, 'SUBOTH', 'Other Subaru Models'),
(current_timestamp, current_timestamp, 1205, 65, 'AERIO', 'Aerio'),
(current_timestamp, current_timestamp, 1206, 65, 'EQUATOR', 'Equator'),
(current_timestamp, current_timestamp, 1207, 65, 'ESTEEM', 'Esteem'),
(current_timestamp, current_timestamp, 1208, 65, 'FORENZA', 'Forenza'),
(current_timestamp, current_timestamp, 1209, 65, 'GRANDV', 'Grand Vitara'),
(current_timestamp, current_timestamp, 1210, 65, 'KIZASHI', 'Kizashi'),
(current_timestamp, current_timestamp, 1211, 65, 'RENO', 'Reno'),
(current_timestamp, current_timestamp, 1212, 65, 'SAMUR', 'Samurai'),
(current_timestamp, current_timestamp, 1213, 65, 'SIDE', 'Sidekick'),
(current_timestamp, current_timestamp, 1214, 65, 'SWIFT', 'Swift'),
(current_timestamp, current_timestamp, 1215, 65, 'SX4', 'SX4'),
(current_timestamp, current_timestamp, 1216, 65, 'VERONA', 'Verona'),
(current_timestamp, current_timestamp, 1217, 65, 'VITARA', 'Vitara'),
(current_timestamp, current_timestamp, 1218, 65, 'X90', 'X-90'),
(current_timestamp, current_timestamp, 1219, 65, 'XL7', 'XL7'),
(current_timestamp, current_timestamp, 1220, 65, 'SUZOTH', 'Other Suzuki Models'),
(current_timestamp, current_timestamp, 1221, 66, 'ROADSTER', 'Roadster'),
(current_timestamp, current_timestamp, 1222, 67, '4RUN', '4Runner'),
(current_timestamp, current_timestamp, 1223, 67, 'AVALON', 'Avalon'),
(current_timestamp, current_timestamp, 1224, 67, 'CAMRY', 'Camry'),
(current_timestamp, current_timestamp, 1225, 67, 'CELICA', 'Celica'),
(current_timestamp, current_timestamp, 1226, 67, 'COROL', 'Corolla'),
(current_timestamp, current_timestamp, 1227, 67, 'CORONA', 'Corona'),
(current_timestamp, current_timestamp, 1228, 67, 'CRESS', 'Cressida'),
(current_timestamp, current_timestamp, 1229, 67, 'ECHO', 'Echo'),
(current_timestamp, current_timestamp, 1230, 67, 'FJCRUIS', 'FJ Cruiser'),
(current_timestamp, current_timestamp, 1231, 67, 'HIGHLANDER', 'Highlander'),
(current_timestamp, current_timestamp, 1232, 67, 'LC', 'Land Cruiser'),
(current_timestamp, current_timestamp, 1233, 67, 'MATRIX', 'Matrix'),
(current_timestamp, current_timestamp, 1234, 67, 'MR2', 'MR2'),
(current_timestamp, current_timestamp, 1235, 67, 'MR2SPYDR', 'MR2 Spyder'),
(current_timestamp, current_timestamp, 1236, 67, 'PASEO', 'Paseo'),
(current_timestamp, current_timestamp, 1237, 67, 'PICKUP', 'Pickup'),
(current_timestamp, current_timestamp, 1238, 67, 'PREVIA', 'Previa'),
(current_timestamp, current_timestamp, 1239, 67, 'PRIUS', 'Prius'),
(current_timestamp, current_timestamp, 1240, 67, 'PRIUSC', 'Prius C'),
(current_timestamp, current_timestamp, 1241, 67, 'PRIUSV', 'Prius V'),
(current_timestamp, current_timestamp, 1242, 67, 'RAV4', 'RAV4'),
(current_timestamp, current_timestamp, 1243, 67, 'SEQUOIA', 'Sequoia'),
(current_timestamp, current_timestamp, 1244, 67, 'SIENNA', 'Sienna'),
(current_timestamp, current_timestamp, 1245, 67, 'SOLARA', 'Solara'),
(current_timestamp, current_timestamp, 1246, 67, 'STARLET', 'Starlet'),
(current_timestamp, current_timestamp, 1247, 67, 'SUPRA', 'Supra'),
(current_timestamp, current_timestamp, 1248, 67, 'T100', 'T100'),
(current_timestamp, current_timestamp, 1249, 67, 'TACOMA', 'Tacoma'),
(current_timestamp, current_timestamp, 1250, 67, 'TERCEL', 'Tercel'),
(current_timestamp, current_timestamp, 1251, 67, 'TUNDRA', 'Tundra'),
(current_timestamp, current_timestamp, 1252, 67, 'TOYVAN', 'Van'),
(current_timestamp, current_timestamp, 1253, 67, 'VENZA', 'Venza'),
(current_timestamp, current_timestamp, 1254, 67, 'YARIS', 'Yaris'),
(current_timestamp, current_timestamp, 1255, 67, 'TOYOTH', 'Other Toyota Models'),
(current_timestamp, current_timestamp, 1256, 68, 'TR7', 'TR7'),
(current_timestamp, current_timestamp, 1257, 68, 'TR8', 'TR8'),
(current_timestamp, current_timestamp, 1258, 68, 'TRIOTH', 'Other Triumph Models'),
(current_timestamp, current_timestamp, 1259, 69, 'BEETLE', 'Beetle'),
(current_timestamp, current_timestamp, 1260, 69, 'VOLKSCAB', 'Cabrio'),
(current_timestamp, current_timestamp, 1261, 69, 'CAB', 'Cabriolet'),
(current_timestamp, current_timestamp, 1262, 69, 'CC', 'CC'),
(current_timestamp, current_timestamp, 1263, 69, 'CORR', 'Corrado'),
(current_timestamp, current_timestamp, 1264, 69, 'DASHER', 'Dasher'),
(current_timestamp, current_timestamp, 1265, 69, 'EOS', 'Eos'),
(current_timestamp, current_timestamp, 1266, 69, 'EUROVAN', 'Eurovan'),
(current_timestamp, current_timestamp, 1267, 69, 'VOLKSFOX', 'Fox'),
(current_timestamp, current_timestamp, 1268, 69, 'GLI', 'GLI'),
(current_timestamp, current_timestamp, 1269, 69, 'GOLFR', 'Golf R'),
(current_timestamp, current_timestamp, 1270, 69, 'GTI', 'GTI'),
(current_timestamp, current_timestamp, 1271, 69, 'GOLFANDRABBITMODELS', 'Golf and Rabbit Models (2)'),
(current_timestamp, current_timestamp, 1272, 69, 'GOLF', ' - Golf'),
(current_timestamp, current_timestamp, 1273, 69, 'RABBIT', ' - Rabbit'),
(current_timestamp, current_timestamp, 1274, 69, 'JET', 'Jetta'),
(current_timestamp, current_timestamp, 1275, 69, 'PASS', 'Passat'),
(current_timestamp, current_timestamp, 1276, 69, 'PHAETON', 'Phaeton'),
(current_timestamp, current_timestamp, 1277, 69, 'RABBITPU', 'Pickup'),
(current_timestamp, current_timestamp, 1278, 69, 'QUAN', 'Quantum'),
(current_timestamp, current_timestamp, 1279, 69, 'R32', 'R32'),
(current_timestamp, current_timestamp, 1280, 69, 'ROUTAN', 'Routan'),
(current_timestamp, current_timestamp, 1281, 69, 'SCIR', 'Scirocco'),
(current_timestamp, current_timestamp, 1282, 69, 'TIGUAN', 'Tiguan'),
(current_timestamp, current_timestamp, 1283, 69, 'TOUAREG', 'Touareg'),
(current_timestamp, current_timestamp, 1284, 69, 'VANAG', 'Vanagon'),
(current_timestamp, current_timestamp, 1285, 69, 'VWOTH', 'Other Volkswagen Models'),
(current_timestamp, current_timestamp, 1286, 70, '240', '240'),
(current_timestamp, current_timestamp, 1287, 70, '260', '260'),
(current_timestamp, current_timestamp, 1288, 70, '740', '740'),
(current_timestamp, current_timestamp, 1289, 70, '760', '760'),
(current_timestamp, current_timestamp, 1290, 70, '780', '780'),
(current_timestamp, current_timestamp, 1291, 70, '850', '850'),
(current_timestamp, current_timestamp, 1292, 70, '940', '940'),
(current_timestamp, current_timestamp, 1293, 70, '960', '960'),
(current_timestamp, current_timestamp, 1294, 70, 'C30', 'C30'),
(current_timestamp, current_timestamp, 1295, 70, 'C70', 'C70'),
(current_timestamp, current_timestamp, 1296, 70, 'S40', 'S40'),
(current_timestamp, current_timestamp, 1297, 70, 'S60', 'S60'),
(current_timestamp, current_timestamp, 1298, 70, 'S70', 'S70'),
(current_timestamp, current_timestamp, 1299, 70, 'S80', 'S80'),
(current_timestamp, current_timestamp, 1300, 70, 'S90', 'S90'),
(current_timestamp, current_timestamp, 1301, 70, 'V40', 'V40'),
(current_timestamp, current_timestamp, 1302, 70, 'V50', 'V50'),
(current_timestamp, current_timestamp, 1303, 70, 'V70', 'V70'),
(current_timestamp, current_timestamp, 1304, 70, 'V90', 'V90'),
(current_timestamp, current_timestamp, 1305, 70, 'XC60', 'XC60'),
(current_timestamp, current_timestamp, 1306, 70, 'XC', 'XC70'),
(current_timestamp, current_timestamp, 1307, 70, 'XC90', 'XC90'),
(current_timestamp, current_timestamp, 1308, 70, 'VOLOTH', 'Other Volvo Models'),
(current_timestamp, current_timestamp, 1309, 71, 'GV', 'GV'),
(current_timestamp, current_timestamp, 1310, 71, 'GVC', 'GVC'),
(current_timestamp, current_timestamp, 1311, 71, 'GVL', 'GVL'),
(current_timestamp, current_timestamp, 1312, 71, 'GVS', 'GVS'),
(current_timestamp, current_timestamp, 1313, 71, 'GVX', 'GVX'),
(current_timestamp, current_timestamp, 1314, 71, 'YUOTH', 'Other Yugo Models');
